### ISSUE TITLE
Kitsuki Yaruma the dragon character in tears of amateratsu is bugged

### ISSUE THREAD

**Issue by Sertor** [gryffon/ringteki#1036]
Courtesy has bug the game in fate phase when he must discard and activate the skill. And The other skill to take facedown a unbroken facedown province never activates.

**Comment by jeremylarner** [comment]
I've submitted a fix for his enters play bug, but I can't replicate the issue with Courtesy.  Please submit a new issue (preferably with a screenshot, or a copy & paste from the game log) if you have this problem again.
