### ISSUE TITLE
Court Games to Dishonor Above Question(s) -- Court Games = wasted card!

### ISSUE THREAD

**Issue by HirumaSan** [gryffon/ringteki#1040]
I was playing tsuke's Lion and had Above Question on a solo Crab Borderlands Defender which he attempted to dishonor. The card was then wasted as I couldn't target myself obviously and it threw the conflict pass phases out of whack in a game

My interpretation is that the option to dishonor should have straight up been illegal as per the selection must change the game state rule

**Comment by jeremylarner** [comment]
Thanks for the report - fix submitted
