### ISSUE TITLE
Breaking a province shows the province name in chat

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#106]
Clicking on a province can break the province and if it's face down reveal what it is.

Need to be a little more determinate about when this happens.

**Comment by jeremylarner** [comment]
Maybe limit revealing and breaking provinces to only during a conflict? I guess I could maybe look at implementing an 'Are you sure?' box, but it seems a lot of work for a temporary feature. Breaking is easy to undo, revealing is less so.

**Comment by gryffon** [comment]
I would think that limited when it can be broken during the phase would
probably be best.

**Comment by jeremylarner** [comment]
I think the breaking is less of an issue than revealing.  Revealing ought to be automatic, you shouldn't ever need to do it manually.  So I may disable click to reveal completely.

**Comment by gryffon** [comment]
That makes sense.

**Comment by jeremylarner** [comment]
Fix submitted
