### ISSUE TITLE
Ambush

### ISSUE THREAD

**Issue by nmetken** [gryffon/ringteki#1060]
Have played multiple games where the card Ambush has frozen up the game shortly after being played, once where my opponent played it and once where I played it.  Also it would not allow me or my opponent to select a second character despite the characters being face up and totaling less than 6 cost.

**Comment by jeremylarner** [comment]
I can't replicate an issue with Ambush.  Can you give me any more info as to what was happening in the game at the time?

If you have this issue again, please take a screenshot and submit it with the bug report.  It makes it so much easier for us to find the problem.
