### ISSUE TITLE
Suggestion: Running total force display during conflicts for spectators

### ISSUE THREAD

**Issue by verspunken** [gryffon/ringteki#1062]
While spectating games it can be difficult to keep track of force totals during a conflict, as they are only displayed in the chat at declaration of attackers/defenders and completion of the conflict. A display similar to that seen by the two players when they have an action window during a conflict would be a good improvement.

**Comment by jeremylarner** [comment]
This really needs some UI work, as it would be nice to have the graphical assets for skill counters, which could be displayed in a similar way to the bid counters we use at the moment.

As a holdover, I've added an announcement to chat after every action in a conflict window.
#1066
