### ISSUE TITLE
Togashi Yokuni  and Way of the Dragon interaction

### ISSUE THREAD

**Issue by manu161** [gryffon/ringteki#1064]
_If Togashi Yokuni has Way of the Dragon attached, he cannot use his own ability twice (because it says "Max", not "Limit"), but he can use the gained ability twice.

"Max" is per ability per card title per player. If Togashi Yokuni gains the ability of Kitsuki Investigator, both characters can use that ability this round (they have different titles). If Yokuni gains the ability of an opponent's Yokuni, he cannot use that ability (no infinite loop)._

**Right now seems that it's impossible to use the gained ability twice.**

**Comment by jeremylarner** [comment]
Thanks for the report - I've submitted a fix #1065
