### ISSUE TITLE
Able to duel characters with a '-' in the required skill (Policy Debate-only issue?)

### ISSUE THREAD

**Issue by SDchk** [gryffon/ringteki#1091]
Not going to go whole hog with bug report this time in case you already know about this one.

As part of a Policy Debate duel, you can select a character with a '-'. This counts that character's skill as 0 for the purposes of the duel.
RAW, you should not be able to duel characters with a '-' for the required skill.

**Comment by jeremylarner** [comment]
Thanks for the report - it's a known issue, there's a fix submitted (#1086), but it probably won't make it onto the live server until monday.
