### ISSUE TITLE
Ikoma Ujiaki

### ISSUE THREAD

**Issue by TPSimon** [gryffon/ringteki#1098]
I could not trigger his ability. I had the Imperial Favour and was he was participating, but left-clicking on him or the favour would not result in triggering his action.

**Comment by TPSimon** [comment]
It seems not to have been a one-off bug, as I could replicate this problem again. Btw, thx for the awesome work you are doing.

**Comment by jeremylarner** [comment]
I can't replicate any issue with Ikoma Ujiaki.  Can you give me a list of steps to replicate the issue?  Alternatively, if you see the same issue again, can you take a screenshot and post it here?

**Comment by TPSimon** [comment]
Okay, I will try. What I can remember was:

I had the Imperial favour both times, giving me +1 Diplomacy and all 4 of my province cards were face up. Maybe there was an issue there.

**Comment by jeremylarner** [comment]
You can't use the ability if all your dynasty cards are face up, because the first part of his ability requires you to flip a dynasty card.

**Comment by TPSimon** [comment]
I am new to L5R and may be wrong, but does it really require to flip a dynasty card? It says "turn each facedown card ... up", what if "each" is 0? (I have been playing FFGs X-Wing heavily and the rule language there accepts "0" as a valid value for terms like "all" and "each".)

**Comment by jeremylarner** [comment]
Action: While this character is participating in a conflict, discard the Imperial Favor – turn each facedown card in each of your provinces faceup. Then, put up to 2 characters from your provinces into play participating in this conflict.

It's the 'Then,... ' which stops it from working. From the RRG:
If the effect text of a card ability includes the word "then," the text preceding the word then must be successfully resolved in full (i.e. the game state must change to reflect the intent of the pre-then aspect of the effect in its entirety) before the remainder of the effect described after the word "then" can be resolved.

- If the pre-then aspect of an effect does successfully resolve in full, the resolution of the post-then aspect of the effect must also attempt to resolve.
- If the pre-then aspect of an effect does not successfully resolve in full, the post-then aspect does not attempt to resolve.

The game state must be changed by the pre-then effect for the post-then effect to trigger.  If you don't flip any cards, the game state hasn't changed, so the post-then part of the effect won't trigger.  This means that the whole ability doesn't affect the game state at all, and therefore cannot be initiated.

**Comment by TPSimon** [comment]
Thank you for this explanation. However, the player would discard the Imperial Flavour, so would this not be sufficient as a change of board state? I am not trying to rule-lawyer here, but to understand the game better. Again, thank you for your efforts.

**Comment by jeremylarner** [comment]
RRG:
> A triggered ability can only be initiated if its effect has the potential to change the game state on its own. This potential is assessed without taking into account the consequences of the cost payment or any other ability interactions.
The effect has to change the game state - paying a cost doesn't allow you to initiate an effect which does nothing.
