### ISSUE TITLE
If Toturi or Hotaru fire a ring on defence, the game treats the ring as the attacker's

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#1099]
While ring effects generally benefit the attacker, actually the ring should be attributed to the player who activated the ability that resolves the ring.

This matters due to Isawa Kaede's immunity

**Comment by SnarkAttack** [comment]
This is actually the way it is supposed to work, as per the developer ruling on the card. Toturi and Hotaru both read "resolve that ring's effect", and all of the ring effects begin with "The attacking player...". If Toturi or Hotaru use their reaction on the defense, the attacker actually does get to fire the ring effect.

**Comment by DragonDayDragon** [comment]
THATS AMAZING AND A LOT of PEOPLE IN MY LGS ARE GOING TO BE DISAPPOINTED

**Comment by jeremylarner** [comment]
The attacker does get the benefit of the ring, and the attacker makes a decision about e.g. what character the ring affects.  However, Isawa Kaede is immune to her controller's opponent's ring effects.  If Akodo Toturi's controller triggers a fire ring on defense, can the attacker choose Kaede and honor her?  The fire ring says 'The attacking player chooses a character in play and chooses to honor or dishonor that character.', so it's definitely down to the attacker to choose a character, and decide whether they should be honored or dishonored.  However, it's Toturi's controller who is resolving the ring effect, so Kaede is immune to the effect, and cannot be targeted

**Comment by jeremylarner** [comment]
The game developers have decided I'm wrong, and that it is actually the attacker that resolves the ring, not just chooses targets for it.  So the game is WAD
