### ISSUE TITLE
Can't see opponent's declared attackers when declaring defenders

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#113]
Can't see opponent's declared attackers when declaring defenders

**Comment by jeremylarner** [comment]
Fix submitted

**Comment by gryffon** [comment]
I think this may be that the greying out of un-selectable cards makes it hard to see the ring around selected attackers

**Comment by jeremylarner** [comment]
Yes, that was the problem.  So I changed the select defenders prompt so that it doesn't grey anything out any more.  This makes it very clear who is in the conflict
