### ISSUE TITLE
Fawning Diplomat

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#1180]
![image](https://user-images.githubusercontent.com/31585532/33204761-7903ffea-d0fc-11e7-983b-e9baecd57cbc.png)

**Comment by SnarkAttack** [comment]
Working on this

**Comment by SnarkAttack** [comment]
Never mind, this already claimed, will delete these comments when I can

**Comment by SnarkAttack** [comment]
Working on this one
