### ISSUE TITLE
Prodigy of the Waves will not ready during pre-conflict

### ISSUE THREAD

**Issue by Suave32** [gryffon/ringteki#1208]
I was testing out the new Prodigy of the Waves.

After winning a water conflict I claimed the water ring. During the next pre-conflict I could not select Prodigy of Waves to activate his Action to ready himself.

**Comment by SnarkAttack** [comment]
Into the Forbidden City card implementations haven't hit live yet. We'll make sure there is a banner at the top of the Home page whenever they do drop.
