### ISSUE TITLE
Embrace the Void did not add fate

### ISSUE THREAD

**Issue by Suave32** [gryffon/ringteki#1226]
Character with 2 fate had Embrace the Void attached. Character wad discarded by Bayushi Shoju. A prompt was given for Embrace the Void to Interrupt. Game stated I gained 2 fate from Embrace the Void but the 2 fate did not register in the fate pool.

**Comment by jeremylarner** [comment]
Thanks for the report - this is a bug with the way Shoju's lasting effect is applied.  I'll try and get a fix submitted

**Comment by jeremylarner** [comment]
I think this is fixed by #1276
