### ISSUE TITLE
Adding glory does not add to stats for honored characters

### ISSUE THREAD

**Issue by KlgDeathYodel** [gryffon/ringteki#1229]
I was in a game this evening and in a military conflict. I was playing Phoenix. I honored one of my characters. Then I added two glory to her with my stronghold, but the glory I added with my stronghold didn't add to my military stats.

**Comment by jeremylarner** [comment]
I can't replicate this problem, and it seems to be working fine in most games.  Were there any unusual circumstances?  If you can grab a screenshot when reporting issues like this it's really helpful.

**Comment by KlgDeathYodel** [comment]
I actually did it last night and it worked fine. It may have been due to a mistake on my end.

    On Wednesday, November 29, 2017 6:10 AM, jeremylarner <notifications@github.com> wrote:
 

 I can't replicate this problem, and it seems to be working fine in most games. Were there any unusual circumstances? If you can grab a screenshot when reporting issues like this it's really helpful.—
