### ISSUE TITLE
Victory Condition

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#123]
There's no check to see if a player has won based on broken provinces

**Comment by jeremylarner** [comment]
I have a fix for this, but I'm concerned that if I implement a game win on the stronghold province breaking, it may lead to accidental concessions where a player clicks on their stronghold province by accident (while trying to use it's ability, or their stronghold).  Any suggestions?

**Comment by gryffon** [comment]
Hmm. Tough question. A confirmation seems to be the only way to avoid that, that I can think of.

**Comment by jeremylarner** [comment]
Added in #636 
There is still no way to manually break a stronghold province, but I'm planning to add it in with manual mode menus

**Comment by jeremylarner** [comment]
Solution in #704
