### ISSUE TITLE
Show multiple copies of card in hand

### ISSUE THREAD

**Issue by Suave32** [gryffon/ringteki#1231]
Currently the system does not show multiple copies when looking at your opponents hand. Most notably now with heavy use of Policy Debate.

For Example: **Player A** uses Policy Debate on **Player B** and **Player A** wins.

This is **Player B's** hand: Court Games x3, Fine Katana, Ornate Fan, Let Go, Mirumoto's Fury x2
The game shows that **Player B** has 8 cards in hand.

When **Player A** gets the prompt to discard a card the prompt only shows: Court Games, Fine Katana, Ornate Fan, Let Go and Mirumoto's Fury. 

**Player A** cannot see which cards are of multiple copies. In an in-person game **Player A** would be able to see the entire hand and know exactly how many of each card their opponent has. It would be helpful to have this improvement in the future.

**Comment by jeremylarner** [comment]
The losing player's hand is displayed in the chat channel, so you can see how many copies of each card they have there.

I will look at seeing whether we can display that info on the prompt as well

**Comment by jeremylarner** [comment]
I've submitted code which should fix this #1237
