### ISSUE TITLE
Back-Ally Hideaway + Dishonored guy

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#1233]
If you put a dishonored guy in back-ally hideaway, you lose 2 honor for some reason.

![image](https://user-images.githubusercontent.com/32277970/33338767-121111aa-d445-11e7-8fbc-9f66ff604946.png)

**Comment by Sliski** [comment]
The same happens with other leave the game effects like Bayushi Liar's Sincerity.

**Comment by jeremylarner** [comment]
Thanks for the report and the screenshot - fix submitted #1234
