### ISSUE TITLE
Steward of Law / For Shame interaction

### ISSUE THREAD

**Issue by simcof** [gryffon/ringteki#1235]
had a conflict, state was:
- opponent had a Steward of Law a the conflict
- I had a courtier at the conflict (a lion one if that matters)

I played For Shame! on his character and he had the option of dishonoring the character (which Steward would prevent)

**Comment by jeremylarner** [comment]
I can't replicate this.  Was the character honored? Steward only stops characters from entering the dishonored state, not characters from moving from honored to ordinary.
