### ISSUE TITLE
Possible Born in War bug

### ISSUE THREAD

**Issue by lufia22** [gryffon/ringteki#1243]
![image](https://user-images.githubusercontent.com/32967160/33418937-ddbc42ba-d56d-11e7-80b6-b42b8d05e443.png)

I attached an image of my game state.
It is not allowing me to play Born in War. I do not see a reason I cannot play it. Moto Horde is a Cavalry type character and I have 2 fate. I see nothing else restricting me from playing Born in War.
I charged Moto Horde, which may be where the glitch originated.

**Comment by jeremylarner** [comment]
Horde can only have weapon attachments, and Born in War is not a weapon.  Thanks for the report and the screenshot though - I really appreciate you making the effort
