### ISSUE TITLE
Togashi Yokuni ability bug

### ISSUE THREAD

**Issue by nbriffa** [gryffon/ringteki#1270]
In my game this evening I used Togashi Yokuni to copy the ability of the card "Akodo Toturi". When I defended the conflict successfully, and reacted with the ability, it resolved the ring effect for my opponent instead of myself.

**Comment by jeremylarner** [comment]
Thanks for the report.  However, I think this is working as designed. The game developers have ruled that Akodo Toturi and Doji Hotaru both benefit the attacker when their abilities are used after claiming a ring on defence.

**Comment by nbriffa** [comment]
Wow, really? I'll have to do some investigating that seems super broken.
Even the player who owned the Toturi didn't expect it to resolve for him
because it was I who had won the conflict. Thank you for the information!
