### ISSUE TITLE
Utaku mediator did not gain buff on turn 1

### ISSUE THREAD

**Issue by rahulbal** [gryffon/ringteki#1278]
It is turn 1. I control a mediator and a giver of gifts, opponent a prodigy of the waves and a scribe. There is no favor in play. Upon initiating my first fire military conflict the Mediator at Meditations on the Tao the military skill computed for my mediator was 0. Should have been 1 as I did not have the favor.

**Comment by SnarkAttack** [comment]
I'll look into this

**Comment by SnarkAttack** [comment]
Fixed in #1279. Spelling is hard sometimes.
