### ISSUE TITLE
Endless plains trigger didn't enforce removal of character on the field

### ISSUE THREAD

**Issue by rahulbal** [gryffon/ringteki#1284]
Turn 1. Playing unicorn again. Opponent is playing crab. I have a Utaku Mediator and Utaku Yumino. Opponent controls Kaiu Envoy and a Stoic Magistrate. Opponent attacks into an Endless plains with the kaiu envoy. It is a void military conflict. This is the first attack this turn. Endless plains triggers and is activated by me, breaking the province and discarding altansarnai who was placed over it. But from the looks of it the opponent did not receive a prompt to discard his kaiu. Or if he did it did not resolve correctly.

**Comment by jeremylarner** [comment]
I can't replicate an issue with Endless Plains.  The game doesn't enforce targeting, and there is always a button you can use to cancel it.  So if your opponent chose to press that button instead of choosing a character to discard, then the game will cancel the ability.

**Comment by YogoGohei** [comment]
Is there a reason that the "done" button is available during mandatory targeting when the mandatory targeting hasn't been done?

I can understand it being there in manual mode, but why is it there (and not grayed out or something) the rest of the time?

**Comment by jeremylarner** [comment]
It's there so that if something goes wrong there's a way to abort without having to resort to /cancel-prompt, which is notoriously buggy.  I'm not sure whether we're at a point where the downsides of having a 'Done' button outweigh the upsides.

**Comment by jeremylarner** [comment]
I should also note that I've submitted new code (#1293) which will put a message in chat if costs are not paid or targets haven't been resolved, so you should be better able to track what's gone wrong with an ability that fizzles.

**Comment by YogoGohei** [comment]
yeah... /cancel-prompt is bad.
is there a reason it can't only be there in manual mode?  Just hide it if not in manual mode?

**Comment by jeremylarner** [comment]
I'll look at trying to hide it outside of manual mode

**Comment by Neophos** [comment]
Would it not be better to rename the button? Instead of "Done", something like "Ignore effect"?

**Comment by jeremylarner** [comment]
I'm trying to rename it Cancel Prompt, and only have it appear in Manual mode
