### ISSUE TITLE
Implacable Magistrate combat error

### ISSUE THREAD

**Issue by Suave32** [gryffon/ringteki#1287]
[Implacable Magistrate](https://fiveringsdb.com/cards/search?q=implacable%20magistrate)

Last night I had an opponent who played this card and functioned normally.

But then he used Charge to bring in a second Implacable Magistrate into the same conflict. His total military combat was reduced to 0. I do not think the card is supposed to function this way. I would assume the card text would let both magistrates contribute their stats in the same conflict. I am just assuming this is a bug in Jigoku and doesn't require a developer ruling.

**Comment by jeremylarner** [comment]
As far as I know, this is working as designed.  If you have two magistrates in the conflict, while they don't stop themselves from counting skill, they will both stop the other from counting skill, meaning that if you have no honored characters in the conflict, your skill will be 0.
