### ISSUE TITLE
Mirumoto Prodigy

### ISSUE THREAD

**Issue by Kwaice** [gryffon/ringteki#1288]
![screen shot 12-02-17 at 03 38 pm](https://user-images.githubusercontent.com/25953788/33516665-e270fdcc-d776-11e7-98c1-fb10b4e9c4be.PNG)

Mirumoto Prodigy seems bugged. 

When she is **not** attacking alone, the opponent still cannot declare more than one defender. 
In this case i couldn't choose Hiruma Yôjimbô to defend along Kisada. I was limited to one defender.

**Comment by jeremylarner** [comment]
Thanks for the report and the screenshot, I'll have a look.
