### ISSUE TITLE
Mantra of Water not firing

### ISSUE THREAD

**Issue by StGregori** [gryffon/ringteki#1292]
Mantra of Water in hand, an unbowed monk in play. Opponent declares attack. I should be able to play Mantra based on the current rules I believe.

Reaction: After your opponent declares a  conflict, choose a Monk character or a character with a Monk attachment – ready that character and draw 1 card.

Checking for Legal Target (all before the dash)
I am required to choose a Monk character or a character with a Monk attachment - Check

I am required to change the game state when it resolves, but NOT required to perform all the effects only as many as possible. I'm not readying anyone but I am drawing a card. - Check

So I would not be able to ready the Monk, but I would draw a card.

Card should be able to resolve regardless as long as my opponent declared Water and I have a Monk in play.

**Comment by jeremylarner** [comment]
From the RRG:
> A card is not an eligible target for an ability if the resolution of that ability's effect could not affect the target at all. (For example, a bowed character cannot be chosen as the target for an ability that reads "Action: Choose a character – bow that character.")
This means that a ready monk is not an eligible target for Mantra of Water, and you cannot initiate an ability which requires a target unless there is at least one eligible target in play.

**Comment by Kwaice** [comment]
I think StGregori is right.

It should fall under the "Resolve as much as the effect" rule. The game state is changed.

A bit like Court Mask, no ?

**Comment by YogoGohei** [comment]
OP is wrong.

A target isn't a legal target if none of the actions effects will successfully resolve. Mantra of Water targets a monk to unbow. If a monk cannot unbow, it is not a legal target.

Before you ask, Shameful Display "gets around this" because it's effect is "honor or dishonor the target". Anyone that can be "honored or dishonored" is a legal choice.

**Comment by StGregori** [comment]
I agree that the action would not be legal if "NONE of the actions effects will successfully resolve." (emphasis mine). But that isn't the case. One of the effects will indeed resolve. Just like Shameful Display. In that case, you cannot resolve it in a manner that attempts to honor a honored character and dishonor a dishonored character, because you MUST change the game state somehow. The target is legal, the game state changes, the action is legal.

JMO.

**Comment by YogoGohei** [comment]
I misspoke.  The relevant rulebook passage is below.  The action needs to effect all targets in some way.  If it can't effect the target, it isn't a legal target.
![image](https://user-images.githubusercontent.com/32277970/33560520-f463335c-d8dd-11e7-99d6-7446ca471fbc.png)

**Comment by jeremylarner** [comment]
The point is that a targeted ability doesn't just have to change the game state, it actually has to do something to the target.  Mantra of Water on an unbowed Monk wouldn't change the game state of that monk at all. Therefore the monk isn't a legal target, and the ability can't be initiated.
