### ISSUE TITLE
Breaking Artisan Academy while card is flipped breaks game state.

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#1295]
Everything the controller of the Academy does after that point causes an incorrect game state error.

**Comment by jeremylarner** [comment]
I can't replicate this - can you tell me what else was happening in the game at that point?  Or give me instructions on how to cause these game state errors?

**Comment by YogoGohei** [comment]
Unfortunately I don't have screen shot.  Will update this case if I see it again.

**Comment by jeremylarner** [comment]
I think this bug is due to an interaction between Academy and attachmonks, and I submitted a fix (#1323) which has been applied to the server.  So I'm going to close this, but there could be another bug to do with academy breaking.
