### ISSUE TITLE
Unbroken Pilgrimage is not canceling Hotaru

### ISSUE THREAD

**Issue by lufia22** [gryffon/ringteki#1321]
I have confirmed this twice. Hotaru attacks Pilgrimage, doesn't break, and it gives opponent option to use her ability and resolve it even though it's not supposed to.

"Pilgrimage cancels ALL ring effects, including those initiated by card effects (e.g. Display of Power, Akodo Toturi, Doji Hotaru)."

https://fiveringsdb.com/cards/search?q=pilgrimage

**Comment by jeremylarner** [comment]
Thanks for the report - A fix (#1310) has already been submitted for this bug, and it will go live with the UI update tomorrow morning
