### ISSUE TITLE
Illustrious Plagiarist

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#1351]
![image](https://user-images.githubusercontent.com/31585532/33733701-6bbf7090-db82-11e7-9759-4178fa28ede5.png)

**Comment by YogoGohei** [comment]
This card's existence means that Spies in Court needs reworked.  

Suddenly the order that the cards end up in the discard pile matters, so the first player should be able to chose that order (If I understand my rules correctly)

**Comment by jeremylarner** [comment]
Yes, I am aware of the issue, but thanks for the reminder. However, I thought that player always chose the order of their own cards in the discard pile?

**Comment by YogoGohei** [comment]
You are correct.  Spies still needs adjusted, just not the way I stated.

![image](https://user-images.githubusercontent.com/32277970/33780146-b6eacb46-dc1d-11e7-8af7-37905a50289e.png)
