### ISSUE TITLE
Backwards Chat text! 

### ISSUE THREAD

**Issue by Alan-Rex** [gryffon/ringteki#1368]
Everytime I write something in the chat in-game, it comes up completely backwards. It's really starting to get under my skin and I'd like to get it fixed! Heres an example: If I type, "you were lucky to break that province!"... it comes up "!Province That Break To Lucky Were You" 

My jigoku username is A-Rex. Please help!

**Comment by Alan-Rex** [comment]
Just to say, this bug is still affecting me but I haven't met any other players with the same issue.

**Comment by Arbuzio** [comment]
Man, you have a free Yoda-Plugin! Thats soooo cool

**Comment by jeremylarner** [comment]
This seems to be particularly prevalent on tablets..
