### ISSUE TITLE
Unable to import new deck from fiveringsdb

### ISSUE THREAD

**Issue by Alan-Rex** [gryffon/ringteki#1374]
Copying & pasting the permalink used to work just fine...and now it doesn't.
Jigoku.online username A-Rex

**Comment by jeremylarner** [comment]
Are you trying to import a deck with pack 5 cards in it?  They aren't on the ringteki server yet

**Comment by Alan-Rex** [comment]
That was the problem, we of the Lion Clan aren't known for our patience. Thanks for the speedy reply
