### ISSUE TITLE
Unreleased Cards

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#1406]
Cards from Imperial Pack #5 are not being marked as "unreleased" even after the release was rolled back yesterday.  Since the pack is no longer "released", those cards should go back to being identified as unreleased, I would think?

**Comment by jeremylarner** [comment]
Well, unreleased is intended to mean that the cards haven't been officially released yet - it's not intended to tell you anything about whether automation is implemented for those cards or not.
