### ISSUE TITLE
Mountaintop Statuary  - Rebuild interaction

### ISSUE THREAD

**Issue by manu161** [gryffon/ringteki#1408]
http://www.cardgamedb.com/forums/index.php?/topic/37991-ruling-mountaintop-statuary/

If I move Mountaintop Statuary to my stronghold province, I can then play Rebuild to shuffle it into the deck and place e.g. The Imperial Palace from my discard pile into my stronghold province

**Comment by jeremylarner** [comment]
Thanks for the report - fix submitted #1410
