### ISSUE TITLE
Cards shouldn't be listing in log after hand reveal

### ISSUE THREAD

**Issue by jlittle576** [gryffon/ringteki#1412]
Notes are not allowed in game, so in order to replicate actual conditions as closely as possible, it would seems that cards shouldn't be listed in the chat log upon reveal.

**Comment by jeremylarner** [comment]
I can see where you're coming from, but there's no way over the internet to enforce the 'no note taking' rule.  Also, if we were to do so, we'd probably need to not log anything in chat.  This leads to ringteki being slightly different to playing at a tournament, but I think that's inevitable.

**Comment by jlittle576** [comment]
>  if we were to do so, we'd probably need to not log anything in chat

What? Why? That doesn't follow.

The issue here isn't that note taking is possible (of course it always is) but that recollection of cards in hand is made trivial in this case. The hand reveal is "temporarily revealed secret info", keyword "temporarily". Just don't print the exact cards to chat log. Just print "opps hand was revealed". Much closer to actual play, and no good reason or technical difficulty to not do it, that I know of anyway.

**Comment by jeremylarner** [comment]
The point I was trying to make is that the game is taking notes for you all the time.  If I don't record what you saw on hand reveals, how about what Iuchi Wayfinder shows you? Apart from the chat log, there isn't a good way to reveal this info.  How about Meek Informant? If Kitsuki Yaruma flips a province back face down, should the info on what that was be expunged from the log?  If you see your opponent take 2 spells from Shrine Maiden into their hand, should that be logged?

At the end of the day, this is a design decision, and it's clearly one that you disagree with.  However, it's the way we've decided the game is going to work.

**Comment by finsterdexter** [comment]
Maybe this should be a feature request that allows "reveal" to actually display cards in a window, similar to how you select a SH province. This is also important for cards that have you "reveal top 4 cards, and take 2" or whatever.

**Comment by jlittle576** [comment]
Dex: Thats basically how it already works, there is a list that pops up and you mouse over it and it shows the card as you mouse over it, that parts great, the user is already duly notified of what cards are revealed. The chat log adds **nothing** except the ability to look back at a later date  (its even hyperlinked, so you see the actual card on mouse over) which can make quite a difference

Jeremy: yes, ideally all forms of temporarily revealed info would have a temporary notification instead of a chat log, e.g. backalley says play chars facedown for a reason, it is the **explicitly intended** function of the card that opp has to rely on memory. But, I realize time is limited with all the new packs and log is just easier. However, policy debate/hand reveal is (a) a lot bigger deal than a single card and (b) a temporary notification solution is already been implemented.
