### ISSUE TITLE
Cunning Magistrate

### ISSUE THREAD

**Issue by jlittle576** [gryffon/ringteki#1413]
Cunning Magistrate's ability (dishonored skilled doesn't count toward conflict resolution) does not work, and cleaning everything up in manual mode after a misfired victory is quite inconvenient.

**Comment by SnarkAttack** [comment]
Just tested this and it seemed to work for me, do you have a photo or can you more specifically describe the situation?

**Comment by jeremylarner** [comment]
Pack 5 isn't live on the server yet

**Comment by jlittle576** [comment]
According to the news feed, Fate is supposed to be live. 

I don't have a screenshot, will take one if see it again.

**Comment by jeremylarner** [comment]
Yes, I think someone was a little enthusiastic with making the announcement.  We are trying to get fate live, but I don't think it's quite there yet
