### ISSUE TITLE
"Not Implemented" indicator

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#1429]
Would it be possible to add a "not implemented" indicator on certain cards within the game itself?  There are a bunch of places you could put it.  Over the "Zoom in" of the card, or as hover text on given cards, as just two examples.

**Comment by jeremylarner** [comment]
I'm hoping from this point on we won't need this.  I'm loathed to invest developer time into it when we could be actually implementing the cards instead.
