### ISSUE TITLE
Watch Commander and Vengeful Oathkeeper

### ISSUE THREAD

**Issue by dumbbells** [gryffon/ringteki#1431]
I think this is a bug. I won a military conflict with a character sporting watch commander. My opponent played a vengeful oath keeper from his hand and I did not get a chance to react to make him lose one honor. If my concept of the timing is correct, I should be able to do this. 

Thanks!

**Comment by YogoGohei** [comment]
https://fiveringsdb.com/cards/search?q=watch%20commander

Putting Vengeful Oathkeeper into play via it's reaction isn't "playing a card"
