### ISSUE TITLE
Spies in Court doesn't seem to work

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#1466]
I hit my opponent with it, so I didn't see the receiving end.  But he claims it didn't prompt him to do anything.

![image](https://user-images.githubusercontent.com/32277970/34112067-71a8ffda-e3d9-11e7-9bd6-964bc0183c93.png)

**Comment by jeremylarner** [comment]
I can't replicate this - I suspect it's another case of a player being prompted, not understanding why and clicking done.  However, I did find a bug with the Spies At Court prompt, and I've submitted a fix
