### ISSUE TITLE
Stone of Sorrows not working

### ISSUE THREAD

**Issue by Arbuzio** [gryffon/ringteki#1482]
I declared conflict on void ring with 3 fate and was able to get it despite char with Stone being ready
![image](https://user-images.githubusercontent.com/32962101/34181744-bc10872e-e513-11e7-9c48-c2bbcc7b0bc3.png)

**Comment by jeremylarner** [comment]
Thanks for the report, and the screenshot! It really helps.  Fix submitted #1484
