### ISSUE TITLE
Deck Validation Checker  can't find stronghold

### ISSUE THREAD

**Issue by JT-Marsh** [gryffon/ringteki#15]
Deckbuilder complains about invalid cards. Not familiar with _.js but _.each syntax, but  based on chrome debugger; check should be for card.card.type. Deck will return a card object, which then has card attribute, which then has a type attribute. 

Suggest changing the iterator variable, to something else to avoid confusion.  

client\deck-validator.js
`
 var stronghold = getStronghold(deck.stronghold);

function getStronghold(deck) {
    var stronghold;
    _.each(deck, card => {
        if(card.type === `'stronghold')` {
            stronghold = card;
        }
    });

    return stronghold;
}
`

Another section of code has the correct addressing
`
//Ensure one province of each element
    _.each(deck.provinceCards, card => {
        if(card.card.element === 'air') {
`

**Comment by JT-Marsh** [comment]
Made fixes for this but noticed. 2 other issues 

1. Strong holds don't have an max influence stat
2. Data structure for pack id/release state is out of date

Current fixes  all use card.card which is confusing, would like to rename one of them card data.

**Comment by jeremylarner** [comment]
Now that fiveringsdb offers deck validation through its api, maybe it would be better to just use that?

**Comment by gryffon** [comment]
That's the eventual intention

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>
