### ISSUE TITLE
Pre-Conflict Action window bugged

### ISSUE THREAD

**Issue by Suave32** [gryffon/ringteki#1509]
Scenario: Turn 1. Toturi attempted to attack a province with Fire Military. I defended with Tsukune. Attached Talisman of the Sun during conflict. Switched the conflict to Shameful Display. Activated Shameful Display. Both Players passed to end conflict.

The action window bugged out for both me and my opponent. After successfully defending the game stated that I won the conflict. The action window as seen below appeared. Neither of us could do anything beyond this point.

Edit: I just realized the game is saying the opponent has 0 conflict left to declare. This was my opponents first conflict and he was first player.

![bug](https://user-images.githubusercontent.com/33984908/34320253-2fa4d4de-e7bb-11e7-92fc-9ef9e13ddf53.png)

**Comment by jeremylarner** [comment]
I think this should be fixed now
