### ISSUE TITLE
integration: initiateConflict in PlayerInteractionWrapper

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#1515]
Create a initiateConflict function in PlayerInteractionWrapper which runs from a preconflict action window. It passes for both players, then has this.player initiate a conflict based on the properties given.  All properties should be optional, and the function should have sensible defaults.
```
this.initiateConflict({
    ring: String
    type: String
    province: Province or CardNameLabelOrId
    attackers: Array of DrawCard or CardNameLabelOrId
    defenders: Array of DrawCard or CardNameLabelOrId
    jumpTo: 'afterConflict'. 'breakProvince', 'resolveRing' or 'claimRing'
})
```

**Comment by artemmikhalitsin** [comment]
I'll work on this, since I have a large portion of this. Since it involves both players' interaction, I think this should be a part of GameFlowWrapper.

**Comment by jeremylarner** [comment]
Yeah, you're right.  GameFlowWrapper or integrationhelper.js is probably a better place for this.
