### ISSUE TITLE
Sacrifice reward takes effect even if sacrifice is prevented

### ISSUE THREAD

**Issue by Rodigee** [gryffon/ringteki#1519]
In two different games my opponent activated Funeral Pyre, then used Iron Mine to prevent the sacrificed character from leaving play. My opponent received a card from funeral pyre even though the sacrifice wasn't fulfilled as per the rules guide here: https://fiveringsdb.com/rules/reference#sacrifice

Despite showing this rules guide entry, my opponents argued that this was a legal play because that's how the software is programmed.

I imagine this is also a problem with other sacrifice cards such as Way of the Crab and other prevent leave play cards, such as Reprieve. Is it possible to have the reward from the sacrifice delayed until all the options to prevent the sacrificed character from leaving play have been passed?

**Comment by jeremylarner** [comment]
Yes. I'm aware of this issue.  You are correct that this is an illegal play, and I am working on fixing it.  It's not a straightforward issue to fix however.

**Comment by jeremylarner** [comment]
Fixed by #1669
