### ISSUE TITLE
Manual moving of facedown cards reveals name

### ISSUE THREAD

**Issue by SnarkAttack** [gryffon/ringteki#1522]
Noticed this watching a game, where a player chose to unpurchase a dynasty character. When moving the facedown card from the province back to the top of the deck, it printed what the facedown card was in chat. Should probably add a check to just display “a facedown card” instead of the actual name.

**Comment by jeremylarner** [comment]
Dragging cards in general needs a refactor.  I'd like to make it so that dragging only works in manual mode, and also to set more criteria for what can/cannot be dragged (e.g. you shouldn't be able to drag provinces or strongholds into the play area)

**Comment by SnarkAttack** [comment]
I can spend some time with this then

**Comment by jeremylarner** [comment]
@SnarkAttack Are you still working on this?

**Comment by jeremylarner** [comment]
Fixed in #1813
