### ISSUE TITLE
Shiba Yojimbo did not trigger

### ISSUE THREAD

**Issue by WhiteOnmyoji** [gryffon/ringteki#1528]
I did not get an option to trigger my Shiba Yojimbo when my opponent targeted my Prodigy of the Waves with Mirumoto's Fury.

**Comment by jeremylarner** [comment]
I can't replicate this - do you have a screenshot, or any more info of what was happening in the game at the time?  If you see this issue again, a screenshot or a copy of the game log really help in tracking down the problem.

**Comment by WhiteOnmyoji** [comment]
will do thank you
