### ISSUE TITLE
Stolen Talisman of the Sun

### ISSUE THREAD

**Issue by Arlomagno** [gryffon/ringteki#1530]
When Talisman of the Sun is stolen (via calling in favors or karada district) I can't play a second copy of it even if I'm no longer it's controller.
Is it normal?

**Comment by jeremylarner** [comment]
> A player cannot take control of or bring into play a unique card if he or she already controls or owns an in-play copy of that card.

If your talisman is stolen, a copy of the card owned by you is still in play, so you cannot bring a second one into play.

**Comment by Arlomagno** [comment]
good to know, thank you
