### ISSUE TITLE
Overlay with important information.

### ISSUE THREAD

**Issue by prozz** [gryffon/ringteki#1535]
Just an idea for discussion. IMHO it would be helpful if UI would help and present some information that needs to be already kept in game state. It could be optional setting.

- show total mil/pol stats on chars with a lot of attachments
- mark used actions with red dot
- mark available actions with green dot

**Comment by jamesoddy** [comment]
There is now a card stats popup that shows the mil/pol stats implemented in #3257 

The used/unused abilities are to be implemented in the future, but this issue is so old that I think it is best to close this for now and start up a new issue if required.
