### ISSUE TITLE
Reprieve/Iron Mine + Way of the Crab

### ISSUE THREAD

**Issue by cyclops2500** [gryffon/ringteki#1538]
Its been ruled that since sacrificing the friendly Crab personality is the part of the cost, using Reprieve/Iron Mine to prevent the friendly Crab character from leaving play means the cost has not been paid and Way of the Crab is cancelled. 

https://fiveringsdb.com/card/way-of-the-crab

**Comment by jeremylarner** [comment]
Thanks for the report - I think this is the same bug as #1519
