### ISSUE TITLE
unable to import deck

### ISSUE THREAD

**Issue by Jeux12sl** [gryffon/ringteki#1541]
Dear Reader,

I try to import the following deck using the import button.
http://www.cardgamedb.com/index.php/legendofthe5rings/legend-of-the-five-rings-deck-share?p=63971&deck=l5rdeck_5a4e0a4519be8&c=4650

I'm getting no error message, no issue, in fact the import window disapear after few seconds, but no deck is imported.
Am I doing something wrong ?

Thanks in advance for the help.

**Comment by jeremylarner** [comment]
Deck import only works from fiveringsdb.com

**Comment by Jeux12sl** [comment]
Oooops sorry for the confusion.
Thanks.
