### ISSUE TITLE
Miya Satoshi discards through Kanjo District even though it is Imperial.

### ISSUE THREAD

**Issue by Atelus** [gryffon/ringteki#1548]
Satoshi sent Kanjo District right to my discard and skipped past it even though it is an Imperial card. Makes the combo unworkable in Jigoku :(

**Comment by jeremylarner** [comment]
I can't replicate this - was there anything else unusual happening in the game at the time?  Do you have a screenshot or a copy of the game log?

**Comment by Atelus** [comment]
I don't, maybe was just a fluke -.- played him and it discarded straight
through Kanjo and on to a second copy of Satoshi, which was real bad given
the deck relies on that haha. If it happens again I'll get a screenshot and
whatnot and make sure it gets to you.
