### ISSUE TITLE
Should be a mark or token to show which personalities has bonus or penalties

### ISSUE THREAD

**Issue by Futsume** [gryffon/ringteki#1561]
In a game i have played, i attacked with 2 keeper initiates in a political conflict. My oponent used the sinister soshi action, giving -2/-2 to one of them. 

When i wanted to use a court games on one of my keepers. I didn't know which one had the penalty, cause the program don't show it. And i had to select one at random. Hoping to choose the one that didn't have the penalty to get a +2 bonus for the battle instead of a +1 bonus only. 

It's not a common problem. But sometimes you need to know which personality has that penalties or bonuses, as it was my problem being two copies of the same personality.

**Comment by harandil** [comment]
+1
There are many situations that this issue might happen. When opponent has two copies of the same personality, play Banzai or other bonuses for it and I want to Assassinate the personality with bonuses.

**Comment by jamesoddy** [comment]
So this is implemented to an extent in #3257 
There is a bit further to go in order to show all effects, but changes to military skill and political skill is now shown.
I'm going to close this issue as it so old ;)
