### ISSUE TITLE
Yokuni activating ability while affected by Cloud the Mind

### ISSUE THREAD

**Issue by b-togo** [gryffon/ringteki#1577]
Board state:
- I have a Yokuni
- The opponent has a Yokuni and 2x Agasha Swordsmith

Actions:
- Opponent uses a Swordsmith to dig
- I copy a Swordsmith with my Yokuni
- Opponent copies a swordsmith with their Yokuni
- I attach Cloud the Mind to opponent's Yokuni
- Opponent was able to click Yokuni to use his ability (they chose to take nothing realizing it was a bug)

**Comment by jeremylarner** [comment]
Cloud The Mind only blanks printed abilities.  In your example, Yokuni already used his printed ability before the CtM was attached.  So he was able to use the ability he gained, which is not printed and therefore not stopped by CtM
