### ISSUE TITLE
Savvy Politician + Pride 

### ISSUE THREAD

**Issue by helanhalvan** [gryffon/ringteki#1578]
If you have an honored Savvy Politician and give it pride with for example Magnificent Kimono, and the Savvy Politician is honored, you can still fire it's ability upon winning a conflict. 

This is one of the few edge cases where the fact that Savvy Politician is honored prevents it from triggering, without there being any player targeting involved. (cards like way of crane)

**Comment by artemmikhalitsin** [comment]
I was able to replicate this. Will look into it.
