### ISSUE TITLE
Dynasty Mulligan doesn't work correctly

### ISSUE THREAD

**Issue by tobinlopes** [gryffon/ringteki#1585]
Hey folks,
I recently had two occurrences of this.

I had three copies of a dynasty character in my initial flop (Yoshi x3, and Kisadax3). In both cases I mull'd all three of them and in each case one copy showed up in my mull. 

So, apparently the cards aren't being "removed" from the deck before getting the next three followed by reintegration into deck then a shuffle. It looks like the three cards are integrated, deck shuffled, then new cards drawn.

-tpl

**Comment by jeremylarner** [comment]
I cannot see how that could possibly happen.  The cards which you get in a mulligan are always the next ones on top of your deck (so if you mulligan all 4 dynasty cards, you will always get the next 4 cards from your dynasty deck).  You can verify this by going into manual mode, looking at your dynasty deck, and then mulliganing all 4 cards.  You will always get the first 4 cards which were in your deck before you took the mulligan.

There's no way you could get the same card back again, unless your deck is smaller than 8 cards.  Are you sure you're not playing with 4 copies of some dynasty cards?
