### ISSUE TITLE
Unable to Login/reset password

### ISSUE THREAD

**Issue by stokesbook** [gryffon/ringteki#160]
Hi,
Made up an account when the site went up a few days ago (when ShamefulDisplay was trying to stream it) Was able to log in fine.  Tried to log in today and it's not accepting my password, when I try to get a password reset, I type the username and check the tickbox in the Captcha, and I get an error saying "Please complete the Captcha correctly" There's nothing in the captcha except a tickbox.  It also won't let me register a new account as my username/email is already taken

My username is the same as here, any help you can offer would be much appreciated

**Comment by gryffon** [comment]
We'll look into getting that fixed

**Comment by lynkfox** [comment]
I am having this same issue.

**Comment by gryffon** [comment]
This will be fixed once the transition to the live site is finished.
