### ISSUE TITLE
Haughty Magistrate: skill count and "[province] is breaking!" message

### ISSUE THREAD

**Issue by moeljartin** [gryffon/ringteki#1611]
After each action, if the attacker's skill count is big enough to break the province, the dialog says something like "Military Water conflict - Attacker: 3 Defender: 2 Public Forum is breaking!" When Haughty Magistrate is involved (possibly other magistrates too), the count does not account for Haughty Magistrate's impact, and the "[province] is breaking" part is not included. The system actual does the count right, as the count shows up correctly in the box with the "Pass" button, and the province will actually break based on accurate counts. It's just reported incorrectly in the dialog box. 

![image](https://user-images.githubusercontent.com/13753958/35706345-0e48a520-076b-11e8-8346-539aa7b859ce.png)

**Comment by jeremylarner** [comment]
Thanks for the report - this is the same issue as #1500
