### ISSUE TITLE
Lion's Pride Brawler should not bow "-" mil characters

### ISSUE THREAD

**Issue by moeljartin** [gryffon/ringteki#1613]
Today I was able to bow a Meek Informant with LPB. The rules are quite clear that anything referencing a  skill value (like LPB) should not be able to target a character with a "-" for that skill. Other examples are duels, Along the River of Gold, Rout/Outwit.

**Comment by jeremylarner** [comment]
LPB can bow characters with a -.  Dash stops duels and doesn't allow your base skill to be switched, but it doesn't stop abilities which compare skill values (e.g. LPB or Routwit).  In those cases, - is considered to be 0.
