### ISSUE TITLE
Talisman of the Sun doesn't allow political conflicts to be moved to Hito District province

### ISSUE THREAD

**Issue by willybn1** [gryffon/ringteki#1622]
Hi, i played game last night and when i tried to use Talisman of the Sun to move an ongoing political conflict to a Province with Hito District face up. (I read HD that it prevents Political conflicts being declared there, but that shouldn't stop the conflict moving there). I couldn't select the province when prompted by the TotS. I don't think there was anything else on the board that could affect this. Thanks for your work on Jigoku.

**Comment by jeremylarner** [comment]
Thanks for the report - fix submitted #1624
