### ISSUE TITLE
Utaku Infantry does not adjust STR when Unicorn characters join conflict

### ISSUE THREAD

**Issue by DoubleAitch** [gryffon/ringteki#1644]
Both Charge and Unicorn Stronghold bought additional Unicorn character into the conflict but the Utaki Infantry's STR did not increase either time.

May also be an issue when Unicorn characters are ejected from a conflict but I have not tested that.

**Comment by jeremylarner** [comment]
I can't replicate this.  There is an issue with the timing of skill totals reported in chat (the game seems to be reporting them before it has applied all relevant effects as in #1500), but the totals listed in the prompt window are correct, and the game seems to always resolve conflicts correctly.

**Comment by DoubleAitch** [comment]
I have checked and can confirm, as you indicated, that it is just the text in the chat window that is incorrect (including the "province is breaking" text).  The values shown in the prompt are correct and conflicts resolve with the correct amount.  Please close or roll into #1500.
