### ISSUE TITLE
Calvary Reserves lets you use opponents Dynasty Discard

### ISSUE THREAD

**Issue by Kurtista** [gryffon/ringteki#1645]
Calvary Reserves allowed me to play 'Calvary' cards from my opponents dynasty discard pile. It was Unicorn vs. Unicorn

**Calvary Reserves**: 

> ...worth of Cavalry characters in **your dynasty discard pile**...

Impact: Not game breaking as long as players enforce

**Comment by jeremylarner** [comment]
Thanks for the report! Fix submitted #1639
