### ISSUE TITLE
5 Let Go no deck reschuffle

### ISSUE THREAD

**Issue by WhiteOnmyoji** [gryffon/ringteki#1646]
I was playing a game against dragon and he played 5 Let Go, I'm submitting it as a bug because I don't want to think of the alternative. Attached is the screenshot and the transcript of the match.

![dragon 2-19 - 5 let go](https://user-images.githubusercontent.com/34945187/36391917-a82a3eba-1576-11e8-9a7b-414678fc4077.jpg)

[Dragon 2-19 - 5 Let Go.docx](https://github.com/gryffon/ringteki/files/1737831/Dragon.2-19.-.5.Let.Go.docx)

**Comment by jeremylarner** [comment]
Fixed in #1793
