### ISSUE TITLE
Rebuild not working on holdings on stronghold provinces

### ISSUE THREAD

**Issue by KazBik84** [gryffon/ringteki#1652]
I try to play 'Rebuild' on the 'Mountaintop Sanctuary' (dragon holding which stacks on the stronghold province as a reaction), to swap it with the 'Imprerial Palace' which was in my discard pile, and I was not able to do that. I asked on FB forum is such action is legit, and the answer was yes.

**Comment by jeremylarner** [comment]
I can't replicate this - what exactly was the problem? When you played Rebuild, did it not let you choose the Statuary? Or not let you select The Imperial Palace?  If you could add a screenshot showing the problem, that would be really helpful.

**Comment by KazBik84** [comment]
I couldn't select mountaintop sanctuary to replace it with rebuild.
Tomorrow I will try to send you screen shot

21.02.2018 15:20 "jeremylarner" <notifications@github.com> napisał(a):
