### ISSUE TITLE
(Suggestion) Background color

### ISSUE THREAD

**Issue by Sotomatic** [gryffon/ringteki#167]
Change the background color to something dark like black maybe please.  The vanilla is killing my eyes.  Great work otherwise!  Thanks

**Comment by gryffon** [comment]
I want to bring over the ability to select and use different backgrounds from throneteki, so this is definitely on the slate.

**Comment by gryffon** [comment]
How about now?

**Comment by Sotomatic** [comment]
This is awesome! Thank you so much!
