### ISSUE TITLE
Ikoma Ujiaki not working while no province to refill ??

### ISSUE THREAD

**Issue by KazBik84** [gryffon/ringteki#1673]
![no ujiaki ability](https://user-images.githubusercontent.com/7277915/36833115-985c75c4-1d2e-11e8-9054-325de4020fb9.PNG)

In this situation I was not able to use Ujiaki ability.

**Comment by jeremylarner** [comment]
Ujiaki's ability has a 'Then...' in the middle of it.  That means that the first part (flip cards in provinces) has to change the game state for the second bit to resolve.  In that case, the first part doesn't change the gamestate, so using his ability is not a legal action.
