### ISSUE TITLE
Couldn't Ready for Battle against Bayushi Kachiko

### ISSUE THREAD

**Issue by racecar0** [gryffon/ringteki#1681]
Opponent attempted to play Ready for Battle after Bayushi Kachiko sent Ujiaki home. Claimed that he was unable to play it. I have no evidence other than his word, since I was the Scorpion player in this scenario. Figured it was worth reporting, just in case.

**Comment by jeremylarner** [comment]
Thanks for the report - the bug is fixed on our development build, which will hopefully be on the live server soon.
