### ISSUE TITLE
Atsuko not working

### ISSUE THREAD

**Issue by Arbuzio** [gryffon/ringteki#1690]
gave all +1, sum = 0
![image](https://user-images.githubusercontent.com/32962101/37235173-e238cae2-23fc-11e8-9967-eb55e0ff8ba9.png)

**Comment by jeremylarner** [comment]
It looks like you attacked with a dishonoured shugenja, and your opponent defended with cunning magistrate, which prevented your character from contributing? Is that not what happened?

**Comment by Arbuzio** [comment]
oh yeah, sorry) drunk L5R after kotei :D
