### ISSUE TITLE
Can we please get an optional 60 minute timer clock?

### ISSUE THREAD

**Issue by gzuvich** [gryffon/ringteki#1691]
In the interest of online tournaments and those of who do not want to spend over an hour playing a game, can we please get an optional 60 minute timer clock for games?

**Comment by Arbuzio** [comment]
+1

**Comment by jeremylarner** [comment]
There's a beta feature which implements chess clocks on the current dev branch, which will hopefully be live soon.  If that isn't adequate and people specifically want a 60 minute timer, it shouldn't be difficult to adapt that code to do a timer instead.

**Comment by jeremylarner** [comment]
Chess clocks are now live on the server if you want to try them. You can activate them using /chess-clocks XX, where XX is the number of minutes on each player's clock (default: 30).  Use the same command to switch them off.  They are a beta feature at the moment, so there is no documentation for them anywhere (game settings/setup/etc).

**Comment by gzuvich** [comment]
I am not looking for a chess clock.  I am looking for an actual count down timer.  "As a player, I want to be able to start a timer clock at the beginning of a match that starts at 60 minutes and counts down to 0 minutes".

I can see keeping the chess clock as an option for players who have asked for that, so I guess this in addition to that.  I know I could use it for my online games due to my own limited amount of play time and it is also useful for online tournaments.

**Comment by gzuvich** [comment]
Yep, definitely want a count down timer.  The chess clock is not doing what I want.

**Comment by KibagamiJubei1** [comment]
+1

**Comment by jeremylarner** [comment]
This is implemented now
