### ISSUE TITLE
Ready for Battle usable after framework bowing

### ISSUE THREAD

**Issue by Saelvarath** [gryffon/ringteki#1706]
I was able to use Ready for Battle to unbow a character that had bowed as a result of combat.

I was playing as a Phoenix with Lion splash VS a Lion. it was the first combat of the first turn (Political Void against my Night Raid), I had a Isawa Masahiro attached with and honoured by Guard Duty against two Venerable Historians.

Once the combat was over and everyone bowed and moved home I got a message to react to Masahiro and the two Historians bowing and Ready for Battle was highlighted. activating the card caused Masahiro to ready.

**Comment by jeremylarner** [comment]
Thanks for the report - Fix submitted #1707
