### ISSUE TITLE
The Path of Man

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#1709]
![image](https://user-images.githubusercontent.com/31585532/37375813-5215ee52-2719-11e8-87c5-de609b23a844.png)

**Comment by jeremylarner** [comment]
I think @Saelvarath is doing this.

**Comment by Saelvarath** [comment]
I have Path of Man and Favour of the Kami coded but I'm having trouble getting everything set up to test them. I could pass the code along if you need them done ASAP.
