### ISSUE TITLE
Mantra of Fire giving the option to select monk/attachments in hand.

### ISSUE THREAD

**Issue by Saelvarath** [gryffon/ringteki#1715]
When Mantra of Fire triggered off of my opponent selecting the Fire Ring Togashi Kazue and Tattooed Wanderer were both highlighted as valid selections. I didn't select them so I can't say if the bug is anything more than visual.

**Comment by jeremylarner** [comment]
Thanks for the report! Fix submitted #1717

**Comment by jeremylarner** [comment]
Fixed in #1722
