### ISSUE TITLE
Able to play two cards a turn?

### ISSUE THREAD

**Issue by Saelvarath** [gryffon/ringteki#1716]
I was about to play Togashi Kazue from my hand (I believe I had her selected but I'm not entirely sure now) but switched my action to playing Daimyo's Favour instead to save a Fate. Once DF had attached to the character the prompt was left giving me the option to play Kazue as an Attachment or a Character. My opponent could not take any action until I had resolved my choice (I selected to play her as a character and canceled when asked how much Fate I wished to play on her but I feel like if I had gone through with either option she would have been played).

**Comment by jeremylarner** [comment]
Thanks for the report! Fix submitted #1718

**Comment by Saelvarath** [comment]
So, I'm a bit of a programmer myself and I'd like to help out if I can.
The site said to contact "me", presumably that means Gryffon, but I'm not sure how to do that.
Any advice on how/where to start would be appreciated.

**Comment by jeremylarner** [comment]
Your best bet is joining the discord: https://discordapp.com/invite/tMzhyND
The first thing most people do is try implementing new cards.  There are 7 on the issues page if you'd like to have a go at that.  Just leave a comment saying that you're doing it (so there's no duplication of effort).  If you're not sure where to start, just ask in the discord
