### ISSUE TITLE
Stronghold should be visible when provinces are selected.

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#173]
Your stronghold is revealed before provinces are selected.  Therefore, you know what your opponent is playing before you select which of your provinces go where.

From the fantasy flght forums:

Feedback from Nate French (one of the developers) on this on August 14 was:
Until the official L5R Organized Play ruleset is finalized, use the following sequence to begin games:
1. Determine first player randomly.
2. Reveal strongholds, then roles.
3. Place provinces.
4. Mulligans.

**Comment by jeremylarner** [comment]
I think we'll probably wait for an official OP ruleset before we make any changes to this.  There will be one out before Worlds at the absolute latest, so it makes sense to wait until it's clarified.
