### ISSUE TITLE
Characters leaving a duel before completion

### ISSUE THREAD

**Issue by brendanquigley** [gryffon/ringteki#1777]
Ref: https://www.facebook.com/groups/L5RLCG/permalink/1677027942362517/?comment_id=1677189815679663&notif_id=1522411343643042&notif_t=group_comment&ref=notif

Obstinate Recruit is the only character this currently applies to, but he can die mid duel, and thus the controller can avoid the consequences of losing.

**Comment by jeremylarner** [comment]
huh, shoju can kill people mid duel too. I'm not a member of that facebook group so I can't see the comment. I'll look at duels fizzling though...
