### ISSUE TITLE
Imperial Favor bug

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#180]
Game sometimes gives Imperial favor to the wrong player. e.g. opponent had a ready Tsukune and 2 claimed rings, but I won the favor with 0 claimed rings and 2 bowed characters.

**Comment by jeremylarner** [comment]
I think this (and the conflict skill bug which occasionally appears) might be caused by Math.max returning strange values as a result of being passed string literals. Going to put together a fix and test it.

**Comment by gryffon** [comment]
Did we get this sorted out?

**Comment by jeremylarner** [comment]
I think so - I haven't had any new reports of it not working recently.
