### ISSUE TITLE
Supernatural Storm leaves Opponent with Priority but no Action Window

### ISSUE THREAD

**Issue by Enigmathetic** [gryffon/ringteki#1833]
I've had back-to-back games in which playing my play of Supernatural Storm sent the action priority to my opponent, but s/he did not have an action window to which s/he could respond.

**Comment by athomaz00** [comment]
That happened to me also with Clarity of Purpose

**Comment by jeremylarner** [comment]
Yeah, I'm trying to track down this bug.  Can either of you tell me whether Shiba Tetsu was in play on the side of the player casting the spell?

**Comment by jeremylarner** [comment]
Fixed in #1834
