### ISSUE TITLE
Forged edict and others

### ISSUE THREAD

**Issue by tokeru** [gryffon/ringteki#1835]
It's quite unfair that the Prompt for reacting with cards like forged edict to an event only appears when you have the oppurtunity to do this. Because when I'm playing against scorpion and play a random event, and the game takes no time wating for a reaction I got the information that he has none. 
There should be an option to activate the react triggers by default, like with the action windows in draw and fate phase.

**Comment by jeremylarner** [comment]
You should be able to change an option setting so that the game prompts you with a 'fake cancel' window.  Unfortunately, a recent update introduced a bug where that window no longer displays.  This has been fixed in #1834
