### ISSUE TITLE
Error with Kyuden Isawa and Against the Waves

### ISSUE THREAD

**Issue by moeljartin** [gryffon/ringteki#1839]
My opponent attempted to used Kyuden Isawa to play Against the Waves. The software told him that it was then "Waiting for Opponent" but I didn't have any potential reactions or a button to pass. No solution with Manual Mode, so we just had to quit. 

I'm on Chrome, not sure what browser he was on, if that matters. 

![image](https://user-images.githubusercontent.com/13753958/38826402-8f5a2b42-4164-11e8-880f-4ec0ab8e9e47.png)

**Comment by jeremylarner** [comment]
This should be fixed now
