### ISSUE TITLE
Deck Building Bug

### ISSUE THREAD

**Issue by KlgDeathYodel** [gryffon/ringteki#1846]
Court Games and Cloud the Mind are doubling up on my decklist. When I select one, it loads two of them in (so if I load in 3x Court Games, it will load in two copies of 3x Court Games). And when I delete it, they both go away. This prevents me from having a valid deck, because the number of conflict cards exceeds 45 and it registers me as having six copies of those cards, rather than just the three I'm trying to put in.

**Comment by jeremylarner** [comment]
I can't replicate this - what browser are you using? Do you have a screenshot?
