### ISSUE TITLE
Sanpuku Seido

### ISSUE THREAD

**Issue by cnecamp1984** [gryffon/ringteki#1847]
When resolution at sanpuku seido takes place glory was not used as the comparative skill and the attacker won with less glory (2 v. 3) but had great political skill.

**Comment by jeremylarner** [comment]
I can't replicate any issues with sanpuku seido - do you have a screenshot or a copy of the game log?

**Comment by cnecamp1984** [comment]
I do not. If it happens again I will be sure to screen shot it
