### ISSUE TITLE
Court Games can't be Cancelled by Censure

### ISSUE THREAD

**Issue by KibagamiJubei1** [gryffon/ringteki#1848]
Court Games was played an no prompt for Censure to came up (yes I had the favor). not sure if there's some other ruling that makes it so that Censure can't cancel Court Games. as far I can tell when CG is an event and should be able to be canceled by Censure when initiating. thanks

Peter Smigelski

**Comment by jeremylarner** [comment]
I can't replicate this - was Tadaka on the board, or was a Guest of Honor in the conflict?
