### ISSUE TITLE
Clarity Of Purpose

### ISSUE THREAD

**Issue by masashigi** [gryffon/ringteki#1850]
Clarity of Purpose failed to keep 2 characters from bowing at the end of a Political Conflict.

Playing clarity.
![clarity of purpose](https://user-images.githubusercontent.com/38586352/39084424-c77f85a2-4543-11e8-864e-3f9c6b726084.png)

Characters bowing after Political Conflict 
![bowed](https://user-images.githubusercontent.com/38586352/39084430-db0efd1e-4543-11e8-976d-2ed55a71e0af.png)

**Comment by jeremylarner** [comment]
You played the Clarity at a conflict at Defend the Wall when you were attacking, and then your second log shows a conflict where you are defending.  Clarity only works for a single conflict.  Did the characters bow at the end of the conflict at Defend the Wall?

**Comment by masashigi** [comment]
My mistake I just didn't read the whole card that it's only for one
conflict.
