### ISSUE TITLE
Swift Magistrate

### ISSUE THREAD

**Issue by tadair231** [gryffon/ringteki#1856]
In game today I had swift magistrate in a military attack...
Other player had Guest of Honor with 1 fate and 1 honor.
It counted Guest of Honor as +1... which I assume is for the honor.
But I'm not sure that is correct it probably should be zero.

Thanks love the work you all have done!

**Comment by jeremylarner** [comment]
Are you sure it wasn't counting the imperial favor?

**Comment by jeremylarner** [comment]
I can't replicate an issue with Swift Magistrate vs honored Guest of Honor
