### ISSUE TITLE
Some conflict characters don't drain fate when played

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#186]
Every event that costs fate (that I have played) removes the correct amount of fate from your pool when played.  Some (all?) conflict characters do not.

I specifically noticed it with Hiruma Ambusher.

**Comment by jeremylarner** [comment]
I haven't been able to replicate this at all.  Can you give me any more details on what conditions it happens in (phase, conflict, etc).  Cards are always free when they are dragged into play - this bug is occurring when you play conflict characters normally, right?

**Comment by YogoGohei** [comment]
Maybe that was the problem. We were dragging rather than clicking.

Will update if I notice it again.
