### ISSUE TITLE
UI layout : 4 lines not 6

### ISSUE THREAD

**Issue by DeedeeTolosa** [gryffon/ringteki#1860]
It is tough to have a board easy to read, often cards are very small or overlaying.
This is imho due to the fact that cards are presented in a serie of 6 cards lines when only 4 are necessary.
I represented the 6 lines in the following snapshot with horizontal redboxes:
![boardlayout](https://user-images.githubusercontent.com/38870013/39454961-66f54634-4cde-11e8-90d0-4f2561fff9de.png)

Lines number 2 and 5 are basically only for stronghold & role and this uses a lot of space.
Layout would greatly improve if stronghold & role were on the same line than characters.

**Comment by jamesoddy** [comment]
Thanks for the feedback.

The UI was overhauled in PR #2441.

I will close this issue, if you have any further suggestions for improvement please let us know with a new issue.
