### ISSUE TITLE
Won conflict and it resolved backwards

### ISSUE THREAD

**Issue by tadair231** [gryffon/ringteki#1881]
![image](https://user-images.githubusercontent.com/15731621/40743111-a20f9e66-641e-11e8-95ba-7881e60fe7f6.png)

I won conflict on defense tried to resolve Doji Hotaru ability and opponent ended up resolving ring and I never got Doji Hotaru effect. Although I claimed earth as seen.

Thinking the above question he put on my guy might be affecting this not sure.

Thanks!

**Comment by jeremylarner** [comment]
That's working as designed.  https://fiveringsdb.com/cards/search?q=doji%20hotaru
