### ISSUE TITLE
Path of Man did not activate after winning conflict with 5 political skills + feral ningyo cannot be played during water conflict

### ISSUE THREAD

**Issue by pukicibai** [gryffon/ringteki#1883]
![image](https://user-images.githubusercontent.com/39718393/40913378-04de0058-6827-11e8-89d4-2d3994c68ab8.png)

**Comment by jeremylarner** [comment]
Thanks for the report - You need to have 5 more than your opponent to trigger Path of Man, and Feral Ningyo is not released yet, so hasn't been implemented
