### ISSUE TITLE
Mouse Over Not Displaying Cards

### ISSUE THREAD

**Issue by SnarkAttack** [gryffon/ringteki#19]
Mousing over cards or provinces that are on the board does not result in the zoomed view in the upper right hand cover

**Comment by gryffon** [comment]
Within the past week or so, the images on fiveringsdb were updated to jpg format. These were in png formerly, so if you still have the old images, that could be why they are not showing up.

**Comment by SnarkAttack** [comment]
It turns out it was just part of the defined game state, where you couldn't get the zoom on face down cards. I fixed that so you can now (mulligans were really hard when you couldn't see the dynasty cards), but I'll have to set some kind of flag so you can't see face down dynasty cards after the mulligan phase has ended.

**Comment by gryffon** [comment]
Right, there is a way to hide face-up cards from the opponent. The decks do this by using "hideTopCard" or something similar. That's likely how we want to treat the dynasty cards during the setup phase, and then set them to be facedown as part of ending the setup phase.

**Comment by SnarkAttack** [comment]
Fixed. Set dynasty cards faceup when provinces first filled, and have getSummary called with hideWhenFaceup=true. After mulligan, all dynasty cards in provinces flipped facedown.
