### ISSUE TITLE
Upholding Authority

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#1914]
![image](https://user-images.githubusercontent.com/31585532/41490690-21423132-70ed-11e8-9b91-8b6c7cce751b.png)

**Comment by suburbaknght** [comment]
When Upholding Authority is used on an opponent who has 0 cards in hand, it causes a game state error.

**Comment by jamesoddy** [comment]
I've added a new commit in PR #2634 to prevent Upholding Authority from triggering if the opponent has zero cards in hand.
