### ISSUE TITLE
Ikebana Artisan

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#1993]
![image](https://user-images.githubusercontent.com/31585532/41689383-3b5e4d90-74e8-11e8-9d3d-c6ef24f0ea89.png)

**Comment by CodeBaboon** [comment]
I'll grab this one.

**Comment by jeremylarner** [comment]
Something to watch with this one, it needs to be able to trigger when the triggering player doesn't have any fate.  That might require some hacks to get around, because I don't think the game will like it.
