### ISSUE TITLE
Deck Builder doesn't reset fully when switching tabs.

### ISSUE THREAD

**Issue by CDMayberry** [gryffon/ringteki#200]
Minor issue:
If you start a new deck, then switch tabs and come back, the preview for the deck is still visible but the editor has switched back to the deck list. If you then try to click 'Edit' or 'Delete' in the preview, the tab crashes.

![mahobug1](https://user-images.githubusercontent.com/2746687/31020451-0bb8eada-a501-11e7-8dd2-da6f42ac2272.gif)

**Comment by gryffon** [comment]
Hmm. I think we'll try and check that on the delete button. Being able to move away from the deck list isn't inherently bad(working on a deck, asking the lobby questions).

**Comment by gryffon** [comment]
On further checking, it doesn't let you resume editing either, so I think we'll just need to clear it. Though we also need to check if that only happens when there are no decks saved yet.

**Comment by CDMayberry** [comment]
Cool, I wasn't sure at the time if it was meant to refresh or not.

It does seem to correctly reset to the deck view when other decks are present.

**Comment by jamesoddy** [comment]
I'd like to think this is no longer an issue - closing
