### ISSUE TITLE
Third Tower Guard

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#2021]
![image](https://user-images.githubusercontent.com/31585532/41781684-15774bc4-7630-11e8-9faf-29eae302c01d.png)

**Comment by NoahTheDuke** [comment]
I’ll take this.

**Comment by jeremylarner** [comment]
I think Kwaice is doing this now

**Comment by Kwaice** [comment]
Yes indeed. No idea how to self-assign though.

**Comment by jeremylarner** [comment]
Only people with collaborator status can be assigned to issues (for reasons I don't really understand).  Just commenting like this is fine.
