### ISSUE TITLE
Kyuden Isawa & Tadaka

### ISSUE THREAD

**Issue by spitfiremoe** [gryffon/ringteki#2061]
Tadaka is not correctly "turning off" Kyuden Isawa. If it does get activated you can't back out of the prompt.

Tadaka came into play via Fushicho.

Controller of Tadaka controlled the Earth Ring.

Was a political conflict at Public forum (with a token on it) and Tadaka was not participating.

**Comment by jeremylarner** [comment]
Thanks for the report, there should be a fix for this coming with BotK
