### ISSUE TITLE
Kyuden Isawa + Tadaka (with CtM) Bug

### ISSUE THREAD

**Issue by LeinadColtrane** [gryffon/ringteki#2087]
Today experienced a situation where I was playing as Phoenix with Kyuden Isawa and my opponent (also Phoenix) had Tadaka in play. I attached Cloud the Mind to Tadaka, but was still unable to activate my stronghold (it wouldn't activate at all).

**Comment by jeremylarner** [comment]
I can't replicate this - if you're struggling to use KI again, can you take a SS of the board (and your conflict discard pile) and post it here?

**Comment by jeremylarner** [comment]
This should be fixed now
