### ISSUE TITLE
Breakthrough

### ISSUE THREAD

**Issue by Empires96** [gryffon/ringteki#2153]
Breakthrough (the Unicorn Event) does not work - no prompt or opportunity to play it is available. Have tested several times. Also unable to play from hand even during manual mode. Thank you.

**Comment by jeremylarner** [comment]
I can't find any issues with Breakthrough, it works fine for me.  If you have this problem again, could you submit a screen shot?

**Comment by Empires96** [comment]
May I ask how you trigger it then? After you break the province? Or claim the ring? How do you actually use the card. I'd there a pop-up? Thanks!

**Comment by jeremylarner** [comment]
If you break a province with your first conflict and you have sufficient characters in play to be able to legally declare a second conflict, it should trigger when the conflict is over (so after the ring has been claimed and all characters who participated in the conflict have been bowed)
