### ISSUE TITLE
Duelist Training Cannot Be Activated

### ISSUE THREAD

**Issue by sigg0** [gryffon/ringteki#2224]
Duelist training cannot be activated in at least some cases.

1. It cannot be activated in a political conflict after a character has been bonzai'd.
(Card text states that it can be activated in a conflict)

**Comment by jeremylarner** [comment]
I can't replicate this problem.  I had no problem activating Duelist Training in a political conflict after using Banzai on the target. Do you have a screenshot?  If you have this issue again, a screenshot would help with tracking the problem down.
