### ISSUE TITLE
Can't upload deck containing Tainted Lands cards.

### ISSUE THREAD

**Issue by ToturiMizu** [gryffon/ringteki#2228]
I've been trying for days to upload a deck that has some cards from Tainted Lands in it. When I paste in the permalink from fiverings and hit the import button, the little import window goes away like usual but there's no new deck. When I remove the Tainted Lands cards, the import works fine. Am I doing something wrong?

**Comment by jeremylarner** [comment]
Try hard refreshing the page (Ctrl-F5).  It sounds like your client might just not have the new data

**Comment by ToturiMizu** [comment]
Well, there it is. Didn't have to do anything. Thanks!
