### ISSUE TITLE
Toturi works on defense

### ISSUE THREAD

**Issue by BlueSapphyre** [gryffon/ringteki#2257]
My opponent used charge on defense to put toturi in play. After they won the fire ring on defense, they triggered toturi's ability and dishonored my guy.

**Comment by markjbyrne81** [comment]
According to the card this is expected behaviour. Torture just have to be participating. 

https://fiveringsdb.com/card/akodo-toturi

**Comment by BlueSapphyre** [comment]
You *can* use his ability on defense, but the attacking player gets the ring effect. If my opponent triggers Toturi on defense, I get the ring effect not my opponent.

"Akodo Toturi's ability can be triggered if you claim the ring on defense. However, the attacking player gets the benefit of the ring effect (notice the wording here is different from Defend the Wall).

RRG v1.1 "Appendix III: Questions and Answers""

**Comment by markjbyrne81** [comment]
I stand corrected :)

**Comment by jeremylarner** [comment]
This should be fixed now
