### ISSUE TITLE
AaN: All and Nothing

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#2296]
![image](http://lcg-cdn.fantasyflightgames.com/l5r/L5C13_95.jpg)
Interrupt: When you would resolve the void ring effect, choose another ring – resolve that ring’s effect instead, draw a card.

**Comment by NoahTheDuke** [comment]
I’ll take this one!

**Comment by jeremylarner** [comment]
They've just made a ruling which will make this harder than I anticipated.  'another ring' refers not to the void ring, but to whichever ring is currently being resolved (which could be a different contested ring if e.g. Kaede has won the conflict).  The physical ring being resolved is not currently passed to the `onResolveRingElement` event, so you may need to rewrite some of ResolveElementAction and ResolveConflictRIngAction to make it work
