### ISSUE TITLE
[Player] plays [card] costing

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#230]
Whenever you play something, in the chat off to the side this phrase appears, but there is no "cost" after the word "costing".  

Not a big deal, but kind of awkward.

**Comment by jeremylarner** [comment]
Again, this is carryover code from Throneteki (I think it's trying to find a gold cost, which is why it's returning blank).  I probably could fix it, but I'd rather focus on implementing events so we don't need to placeholder any more.
