### ISSUE TITLE
Display of Power

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#236]
There is no window to play this card.  Would it be possible to add a "react to winning conflict" window, or something, until this card is implemented in full?

Every time it comes up it causes some havoc because, inevitably, the attacker has already declared themselves the winner and resolved the ring before you can type out STOOOOOOOOOP.

**Comment by jeremylarner** [comment]
I don't really want to implement a new prompt for a placeholder.  I will put it on my list of priority cards to implement.  The cancellation of ring effects looks like it might be a headache though, so I may just partially implement it.

**Comment by YogoGohei** [comment]
Understandable.  Anything you can do to mitigate the timing headaches this card causes would be very helpful.

**Comment by jeremylarner** [comment]
So it took 3 hours, but I think I've found a good way to implement it completely.  PR submitted #242
