### ISSUE TITLE
Ofushikai won't equip on Seal of the Phoenix'd Yoritomo

### ISSUE THREAD

**Issue by Mattie** [gryffon/ringteki#2391]
_Ofushikai_ doesn't allow playing on _Yoritomo_ with a _Seal of the Phoenix_ on him. Possibly won't allow any Phoenix-sealed unique character to wield it. It's important to note that _Yoritomo_, in theory, should be able to wield it and also use its ability if he has a _Seal of the Phoenix_.

**Comment by markjbyrne81** [comment]
I will take a look

**Comment by jeremylarner** [comment]
Ofushikai has been coded to check printed faction for some reason

**Comment by markjbyrne81** [comment]
fixed in PR #2399
