### ISSUE TITLE
Deck Invalid

### ISSUE THREAD

**Issue by solon26** [gryffon/ringteki#2401]
Hello.  One of my decks has been labeled invalid which has caused a bug whenever I log in and try to load any of them.  The system reports it is loading from server but I need to refresh 1 or more times to load my decks.  All start as invalid until I click on each one; which they will then reset to valid except for my Unicorn deck.  I cannot select it so it remains locked in the invalid state.  This I believe is causing the "loading decks from server" issue each time I go back to look at my decks.

**Comment by jeremylarner** [comment]
@gryffon is this a database issue?
