### ISSUE TITLE
Extra Large Cards Show up Under Role card / Stronghold

### ISSUE THREAD

**Issue by ravenwolfxiii** [gryffon/ringteki#2403]
Hi, due to the size of my monitor (52"), I have to use extra large cards so I can actually see the mil/pol values. But whenever I use the extra large cards setting, the cards start showing up underneath my role card / stronghold when I play them. It looks like the anchor point for them being displayed actually gets moved underneath them when they are zoomed in like that. Because of this, I can't use Jigoku at all. Thanks!
Images:
Extra Large Cards: https://imgur.com/T1kxVaX 
Without Extra Large Cards (And unreadable): https://imgur.com/73mtk2b

**Comment by jeremylarner** [comment]
Your monitor isn't tall enough to fit 6 rows of Extra Large Cards.  The game layout needs 6 rows of cards (1 row for provinces, stronghold and cards in play for each player).  I'd recommend trying to resize the window and zoom in/out until the cards are as high as 1/6 of the space you have available.  I'm afraid at the moment, there's no way to make the cards any bigger than that without using the card zoom
