### ISSUE TITLE
uniqueness rule not properly enforced

### ISSUE THREAD

**Issue by jrekier** [gryffon/ringteki#2404]
The uniqueness rule has been changed months ago, yet is not properly enforced online:
[https://fiveringsdb.com/rules/reference#unique-cards](url)

**Comment by jeremylarner** [comment]
Perhaps you could give me some more detail on what exactly is the problem?

**Comment by jrekier** [comment]
Sure. 
Here is the ruling on playing unique cards (from link above)

> A player cannot bring into play a unique card owned by his or her opponent if that opponent controls an in-play copy of that card.

As it is right now, opponents are able to overrule this and bring copies of unique characters owned by their opponents in play.

**Comment by YogoGohei** [comment]
That isn't what the rule means.

It means they literally cannot bring into play a copy owned by their opponent if that opponent controls a card.

For example, if your opponent has a copy of Doji Shizue in play, you cannot bring in a copy owned by that player with something like Shosuro Actress.

**Comment by jrekier** [comment]
is that really what this means ? Sh*t that's unclear. Thanks
