### ISSUE TITLE
Graphical Bug - Ring images broken when selecting effect

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#2416]
![image](https://user-images.githubusercontent.com/32277970/43846857-585ba3f8-9afd-11e8-8cd6-99437c3a8d7b.png)

**Comment by jamesoddy** [comment]
Fixed in PR #2575 

Now shows as:

![image](https://user-images.githubusercontent.com/958931/47907782-ca3ede80-de83-11e8-8041-aa14d58965e7.png)
