### ISSUE TITLE
Issue loading decks when there are no decks

### ISSUE THREAD

**Issue by rahulbal** [gryffon/ringteki#2420]
I am observing an issue when I login after having deleted all my decks.

I am trying load the decks page but I am constantly hit with this message "Loading decks from the server..."

I was able to get this to work once. I tried saving a deck. But after this it still doesn't load correctly.

**Comment by jamesoddy** [comment]
Apologies that you received no reply to this (until now :) ).

I'm closing this issue due to its age and the problem has likely been fixed, if you still have problems, please open up a new issue.
