### ISSUE TITLE
Loading decks from server error

### ISSUE THREAD

**Issue by Hinomura69** [gryffon/ringteki#2423]
Keep getting this message when trying to select a deck, join a game, or edit decks. Locks things up and won't do anything else. Running on the latest version of Firefox.

**Comment by jase2224** [comment]
I've been having this issue for awhile. I log in and I get the message, "Loading decks from the server..." I've tried logging in primarily with Chrome, and just tried it on Edge. I've cleared my cache, browsing history, and other common browsing techniques to try and get it to load. Nothing seems to work.
