### ISSUE TITLE
Hisu Mori Toride Unicorn

### ISSUE THREAD

**Issue by Anfalass** [gryffon/ringteki#2424]
I can't build a new deck with this stronghold because it has the same name than the Lion one.

**Comment by CDMayberry** [comment]
Right now importing it has an issue, but it is possible to add it. Go into a deck and type into the Card field 'hisu'. Two cards should pop-up, both called Hisu Mori Toride. Click and add the second one. The preview will still show the Lion stronghold but it will correctly show the Unicorn SH in a match.
