### ISSUE TITLE
Steward of Law/Ring of Fire

### ISSUE THREAD

**Issue by falrec** [gryffon/ringteki#2429]
I don't think I should be able to dishonor someone using the Ring of Fire in a conflict I won using Steward of Law. Technically he's still participating in a conflict during the framework step where you trigger ring effects as winner.

**Comment by Kwaice** [comment]
Are you sure the character'status didn't just go from honored to normal ? 

Steward of Law doesn't stop that, he just stops character from becoming dishonored.

**Comment by falrec** [comment]
Now that I think about that game, you're right. My bad.
