### ISSUE TITLE
Dishonored Nezumi Infiltrator leaving play caused Server Error

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#2431]
This is the second time I saw this happen.  Both times it was a dishonored Nezumi Infiltrator.  Both times the error below appeared when the Infiltrator died in fate and controller didn't lose honor.
![image](https://user-images.githubusercontent.com/32277970/44424479-384b5900-a557-11e8-823b-b552e05ca293.png)

**Comment by CDMayberry** [comment]
Confirmed, I've narrowed the bug down, still gotta figure out a solution.

**Comment by jeremylarner** [comment]
Thanks for this, I spent a while looking for this bug, but I hadn't realised the Nezumi needed to be not ordinary to trigger it
