### ISSUE TITLE
Seeker of Knowledge possible bug

### ISSUE THREAD

**Issue by CDMayberry** [gryffon/ringteki#2435]
Watched a Crane vs Phoenix game. Crane player attacked KM for Air which got swapped to Water. Crane player then dropped SoK and won by 1, which then should have given him the choice of rings. According to him it did not give him the option to select the Air ring. Other factors of note: Phoenix player had Kaede in the fight. 

Throwing it in here so I remember. If someone wants to check it out feel free, but I'm planning to look at it when I'm not busy.

**Comment by jeremylarner** [comment]
Did he resolve the water ring?  I get this 'bug' reported a lot because players don't realise they need to click the ring they want to resolve...

I guess it could actually be a legitimate bug, but I've never found it when I looked

**Comment by CDMayberry** [comment]
That was my first thought, he seemed genuinely like it wasn't working so I thought I'd check into it.

**Comment by majorminion** [comment]
Set up the original scenario as described but was correctly prompted to select a highlighted ring to the left as expected.  The center prompt itself only shows the "Choose a ring" text & "Do not resolve any rings..." selectable button; the highlighted ring on the side is what actually needs to be selected.  Maybe they were expecting the option to be in the center prompt?

Other general combinations of scenarios run through as a sanity test to shake out other possible circumstances:
-SoK initiates fight
-SoK on defending side
-SoK played into defense
-SoK played into offense
-SoK played while Ring of Air already selected
-Kuroi triggered to change from Ring of Air to other ring
-Kuroi triggered to change from other ring to Ring of Air
-Kaede on defense
-Kaede on offense
-Offense only has skill from relevant Imp. favor
-Defense only has skill from relevant Imp. favor
-Province breaks
-Province unbroken
-Attacker wins
-Defender wins
