### ISSUE TITLE
(Suggestion) Remove the hand popup when spectating

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#244]
Would be better to have Hand Size like your opponent

**Comment by gryffon** [comment]
Fair point, but I do think spectators like knowing what is in the hand, whether that's a requirement or not is up for discussion.

**Comment by gryffon** [comment]
I think we'll disable it for now, and in the future maybe just make a
display that has both hands? With player permission of course.

**Comment by gryffon** [comment]
Hand removed for spectator in #684
