### ISSUE TITLE
Fight On allowed within Lion Keeper of Fire Deck

### ISSUE THREAD

**Issue by paulryanclark** [gryffon/ringteki#2440]
Spectated a game where a player had "Fight On" a Water Role only card allowed as "Valid" in Lion's Keeper of Fire.

**Comment by markjbyrne81** [comment]
I will take a look

**Comment by jeremylarner** [comment]
It's an error in the 5rdb data, Fight on isn't marked as having a role restriction.
Needs a PR fixing it to that repo

**Comment by jeremylarner** [comment]
I submitted a PR to the fiverings data repo

**Comment by jeremylarner** [comment]
My PR has been merged, so fiveringsdb should have the correct data. However @gryffon you'll need to run the fetchdata script to update our DB
