### ISSUE TITLE
not sure what caused it but it wasn't allowing me to declare attacks.

### ISSUE THREAD

**Issue by devilsace** [gryffon/ringteki#2442]
opponent had the crane bird guy. i had the dreamer and miya mystic out. it would ask me if i want to pass on my action... but then would auto pass my conflict declarations..  it was weird...

**Comment by CDMayberry** [comment]
Hm, do you have any more to go off of? IE was anyone bowed, is this the first conflict, had the crane bird dude triggered it's action yet?

**Comment by devilsace** [comment]
this was the second round with the bird guy out. and the bird guy had first conflict and attacked. he also had the ready and honored character province out. he used that both rounds to ready the bird.

**Comment by CDMayberry** [comment]
One last piece, your dudes were both unbowed, or at least the guy who was *not* targeted by the bird's stealth was unbowed correct?

**Comment by devilsace** [comment]
dreamer was unbowed. mystic was bowed.

**Comment by CDMayberry** [comment]
Was dreamer the target of the Bird's stealth/reaction? If so then he can't be declared as an attacker and it will auto-skip because technically nobody can be declared as a attacker.

**Comment by devilsace** [comment]
dreamer didn't have covert.  if the bird targeted him thinking it had covert then that's the problem. but it wouldn't allow me to declare an attack. it would ask me if i had an action. i would hit pass, then it would skip my conflict declaration like i had no one readied.

**Comment by YogoGohei** [comment]
What does dreamer having covert have to do with anything?

If dreamer was hit by your opponent's Tenku Sensei, and you have no other unbowed guys, then you have no one that you can legally attack with and the game (correctly) skipped that step.
