### ISSUE TITLE
Shiba Tsukune + All and Nothing

### ISSUE THREAD

**Issue by IsawaJim** [gryffon/ringteki#2455]
When I use Shiba Tsukune to resolve the void ring, it doesn't let me interrupt with All and Nothing.

Thank you for your time and effort!
~Isawa Jim

**Comment by jeremylarner** [comment]
Thanks for the report - this bug has been fixed, but it hasn't been deployed to the live server yet. Should be resolved soon

**Comment by IsawaJim** [comment]
Okay.  I'm not sure what the process is for uploading it to the live server, I just tested it and it still seems present.  I'm not sure if that means it hasn't been uploaded yet, or if it is still bugged, but I thought I should say something in case it was the latter.

Thank you again for all of your hard work!
