### ISSUE TITLE
Force of the River and empty Dynasty Deck

### ISSUE THREAD

**Issue by moeljartin** [gryffon/ringteki#2458]
My opponent was at 6 honor with 1 card in dynasty deck and three facedown cards in provinces. He triggered Force of the River, which we (and the Discord advanced rules channel) believe should only trigger the framework "lose 5 honor and reshuffle" effect once. Jigoku triggered it multiple times (thus causing a game loss), once for each card that he couldn't refill before reshuffling.

**Comment by jeremylarner** [comment]
This should be fixed in the deployment of UotE
