### ISSUE TITLE
UotE: Bayushi's Whisperers

### ISSUE THREAD

**Issue by CDMayberry** [gryffon/ringteki#2460]
![whispers](https://cdn.discordapp.com/attachments/356854154003480596/489811280136372235/l5c15_bayushis-whisperers_a5.png)

This one is probably the hardest at the moment, because you can name _any_ card, not just the ones in hand.

Notes per Jadiel: "My best idea so far is we get them to pick from cards in hand or in provinces, and add a 'something else' option, and let them work it out manually"

**Comment by YogoGohei** [comment]
The card is called "Bayushi's Whisperers"

Thread title is wrong.  I just wanted to point that out before a card with the wrong name winds up in the code.
