### ISSUE TITLE
UotE: Kitsuki Shomon

### ISSUE THREAD

**Issue by CDMayberry** [gryffon/ringteki#2485]
![shomon](https://images-cdn.fantasyflightgames.com/filer_public/2a/89/2a89d81a-f9a5-4b12-ac3a-6c2287b682a3/l5c15_kitsuki-shomon_a6.png)

**Comment by jeremylarner** [comment]
Currently, the ruling we have on this is that this ability cannot be used while the character is dishonored.  I suspect there is a slight possibility that might change, but I think it's unlikely, and we should probably code it so it works that way
