### ISSUE TITLE
Ofushikai

### ISSUE THREAD

**Issue by jesbart** [gryffon/ringteki#2500]
Ofushikai attached to Shiba Tsukune does not trigger its Champion ability

**Comment by CDMayberry** [comment]
Hm, can add anymore info about the board state? We have a basic test for Ofushikai + Tsukune and it's passing, I'd suspect a combination of other effects would be the source of the problem.

1. Was she attacking or defending? What was the province? Who was she facing?
2. Did she have additional attachments or effects played on her?
3. Were there any active lasting effects like Hida Kisada?

**Comment by jesbart** [comment]
A couple games I played where she is the participating and has ofushikai, ability prompt doesn't come up when I click on it.
