### ISSUE TITLE
Provinces not refilling after sac'ing a Holding

### ISSUE THREAD

**Issue by tobinlopes** [gryffon/ringteki#2534]
Hey folks,

In two different games a holding was sacrificed (Iron Mine, Imperial Storehouse) and the province didn't refill. IM was on a broken province and IS was on an unbroken province but neither refilled.

Thanks,
Tobin
-tpl

**Comment by argon-wolf** [comment]
Happened in a game i was just in as well. opponent sacd a storehouse on a broken province and I sacd a storehouse on an unbroken province, neither refilled

Pretty pressing issue, since it pretty much breaks the game and we couldnt figure out a way to get past in in manual mode
