### ISSUE TITLE
Peasants Advice Reveals Face Down Provinces in Character Selection Prompt

### ISSUE THREAD

**Issue by Fite-Ian** [gryffon/ringteki#2560]
When playing Peasants Advice, a character must be chosen to be dishonored and a province to be peeked at.  Like with most events, it's possible to cancel playing PA before selecting a character to target, however after a province has been targeted but before a character is selected the name of the province is included in the prompt even if it is face down.  It is possible to initiate and cancel playing PA to see the names of all of the opponent's provinces without actually playing it.

**Comment by jamesoddy** [comment]
Confirmed.  Screenshot:

![image](https://user-images.githubusercontent.com/958931/47207661-b3789200-d383-11e8-96da-cfb3d2652df0.png)

Opportunity to cancel by opponent also does not appear until after the province has been revealed.
