### ISSUE TITLE
Attachment issues

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#257]
You cannot drag an attachment to the discard pile should something destroy it (Let Go)

Attempting to use /give-control with an attachment (Calling in Favors) results in odd behavior.  In our case, this created a second copy of it on the board, floating in the void between our two game areas.  Bowing one of them caused the other to bow.  It was very strange.

**Comment by jeremylarner** [comment]
I can't replicate your issue with not being able to drag attachments to the discard pile.  It seems to be working as expected for me.  Was there some other situational factor in that game?

/give-control is code we've inherited from throneteki, and is likely to be unstable.  I don't think there are any gain control of attachment effects in thrones, so it doesn't surprise me that it doesn't work.  Thanks for letting us know though.

**Comment by YogoGohei** [comment]
Discarding from play does work in solo play now (I just tested it)

We could not do this in a two player game yesterday.  I will need to try it again.  It might be fixed.

**Comment by YogoGohei** [comment]
I could be wrong, but I think the only card in the game, right now, that changes the control of an attachment is Calling in Favors.  If you could add that to the "implement sooner rather than later" list, that would be helpful.

**Comment by jeremylarner** [comment]
It is on my list, but the control code has been through a major refactor in throneteki and I want to backport a lot of those changes before I implement any cards which mess with control.
