### ISSUE TITLE
Doji Shigeru did not trigger.

### ISSUE THREAD

**Issue by TPSimon** [gryffon/ringteki#2573]
I had revived my opponent's Doji Shigeru into a conflict and he knocked her out with For Shame, yet, he didnt't have to discard. At least I cannot remember missing the opportunity or misclicking.

I have attached the log and boldened the important section.

Thanks for you effort.

dive1983 uses Artisan Academy to reveal the top card of their conflict deck
Noodles uses City of the Open Hand, bowing City of the Open Hand to take 1 honor from
dive1983
dive1983 passes
Noodles passes
dive1983 passes their conflict opportunity as none of their characters can be declared as an attacker
dive1983 passes
Noodles passes
Noodles is initiating a political conflict at Magistrate Station, contesting the earth ring
Noodles takes 2 fate from the earth ring
Noodles has initiated a political conflict with skill 4
dive1983 does not defend the conflict
dive1983 plays Steward of Law into the conflict with 0 additional fate
Political Earth conflict - Attacker: 4 Defender: 1
Attacker is winning the conflict - Magistrate Station is breaking!
Noodles passes
**dive1983 plays For Shame! to bow Shosuro Actress
Political Earth conflict - Attacker: 1 Defender: 1
Attacker is winning the conflict
Noodles uses Shosuro Actress, sacrificing Shosuro Actress to put Doji Shigeru into play in the conflict
Political Earth conflict - Attacker: 4 Defender: 1
Attacker is winning the conflict - Magistrate Station is breaking!
dive1983 plays For Shame! to bow Doji Shigeru
Political Earth conflict - Attacker: 1 Defender: 1
Attacker is winning the conflict
Noodles
Why didnt her ability trigger?**
Noodles passes
dive1983 passes
Noodles won a political conflict 1 vs 1
Noodles resolves the earth ring, drawing a card and forcing dive1983 to discard a card at random
dive1983 discards Voice of Honor at random
dive1983 plays Mark of Shame, attaching it to Yogo Hiroue
dive1983 uses Mark of Shame to dishonor Yogo Hiroue
Noodles passes
dive1983 passes
dive1983 passes their conflict opportunity as none of their characters can be declared as an attacker
dive1983 passes
Noodles passes
Noodles is initiating a military conflict at Magistrate Station, contesting the air ring
Noodles takes 1 fate from the air ring
Noodles has initiated a military conflict with skill 2
dive1983 does not defend the conflict
dive1983 passes
Noodles plays Banzai! to grant 2 military skill to Yogo Kikuyo
Noodles chooses not to lose an honor to resolve Banzai! again
Military Air conflict - Attacker: 4 Defender: 0
Attacker is winning the conflict - Magistrate Station is breaking!
dive1983 passes
Noodles passes
Noodles won a military conflict 4 vs 0
dive1983 loses 1 honor for not defending the conflict
Noodles has broken Magistrate Station!
Noodles chooses to discard Kakita Yoshi
Noodles resolves the air ring, taking 1 honor from dive1983
dive1983 passes
Noodles passes
Noodles succesfully claims the Emperor's favor with total glory of 7 vs 0
Noodles claims the Emperor's political favor!

**Comment by jeremylarner** [comment]
Thanks for the report - fix submitted
