### ISSUE TITLE
Master Alchemist didn't trigger Young Rumermonger

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#2576]
![image](https://user-images.githubusercontent.com/32277970/47922827-5b1ab780-de8e-11e8-8b92-105dcc9cffd7.png)

Master Alchemist was used to change Togashi Mitsu from dishonored to normal.
Young Rumormonger was not given a chance to trigger.
Unless I am missing some ruling somewhere, I think I can move that to someone else.  He did have another normal character to move it to.

**Comment by jeremylarner** [comment]
Thanks for the report - fix submitted for this
