### ISSUE TITLE
Togashi Mendicant Ability Bug

### ISSUE THREAD

**Issue by ulzeta** [gryffon/ringteki#2636]
Togashi Mendicant ability triggers during the fate phase and I can choose the top three card on my dynasty deck. However, at the start of the next round, the cards that show up on my provinces are completely unrelated cards that I don't choose with Togashi Mendicant's ability.

**Comment by jamesoddy** [comment]
We are missing a test for Togashi Mendicant, so I will look to write one of those.  Can anyone else confirm if mendicant is working/not working for them?  I will try and replicate.

**Comment by xWorkerBeex** [comment]
Thing to note about Mendicant is that the cards you rearranged won't refill your provinces if you do not discard face-up cards in the Regroup Phase of that turn. 

When I used Mendicant to rearrange my cards and discarded one of my face-up cards this turn, I always flipped the card that I chose to be on top.

**Comment by ulzeta** [comment]
I have empty provinces before I have to refill it so I'm sure it's not working...

I choose Togashi Tadakatsu, Togashi Yokuni, and one other but the one that shows up are Agasha Sumiko and a holding.

**Comment by jamesoddy** [comment]
Togashi Mendicant will (usually) only be relevant if you choose to discard any dynasty cards from your provinces in the Regroup Phase.  I'm not sure if that's what happened based upon your description in your example above.

So start of fate phase -> trigger mendicant
top 3 cards of dynasty deck are now (Tadakatsu, Yokuni, "one other")
During Regroup -> discard 1 card from 1 of your provinces
The refilled card is now Tadakatsu
The top 2 cards of your dynasty deck are now Yokuni and the "one other"

**Comment by ulzeta** [comment]
Ah... I understand now... Yep, it's a misunderstanding on my part...
