### ISSUE TITLE
My Ancestor's Strength, leading into Way of the Lion

### ISSUE THREAD

**Issue by SimplyShane** [gryffon/ringteki#2646]
Hello.  I have noticed on Jigoku that this combo (First playing MAS on a Lion shugenja, then following up with a Way of the Lion), does *not* work.  

Why?  Is there anything in the rules preventing it?  Nothing seems to indicate why it wouldn't work...but it certainly does not on the site.

**Comment by jamesoddy** [comment]
MAS is a set effect, Way of the Lion is a multipler effect.  Set effects always trump other effects.  The rulings on https://fiveringsdb.com/card/my-ancestor-s-strength should make it clear along with the modifiers section of the RRG https://fiveringsdb.com/rules/reference#modifiers.
