### ISSUE TITLE
Stolen Secret Card is Face Up

### ISSUE THREAD

**Issue by Fite-Ian** [gryffon/ringteki#2654]
The card removed from play by Stolen Secrets is visible to the opponent and spectators even though SS specifies that it is removed face down.  I'm not sure if players are allowed to look at cards they own out of play, but I'm pretty sure it should be hidden to somebody.

**Comment by jamesoddy** [comment]
Thanks for the report.  We are aware of the problem and a fix is in the works, but we are still working out some of the details.  You are right that it certainly should be facedown and hidden from your opponent.  To be honest, I'm not sure if you should be able to look at it yourself out of play - I expect you are meant to, but not sure if there is a ruling on that :/

**Comment by jamesoddy** [comment]
The fix has been merged and should be deployed soon (if not already!).
