### ISSUE TITLE
CotE - Warm Welcome

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#2750]
![image](https://user-images.githubusercontent.com/31585532/50740842-b3eb3100-11ec-11e9-84be-44e5174d84d8.png)

**Comment by SArendeli** [comment]
I can take this one

**Comment by jeremylarner** [comment]
This looks like Kyuden Isawa or Togashi Mitsu, but it's actually templated differently.  I think it needs two game actions (playCard and moveCard), not a post handler

**Comment by jeremylarner** [comment]
Basically, you want something like Togashi Mitsu, but instead of including a `postHandler`, you want a separate `moveCard` game action (so `gameAction` should be an array with `playCard()` and `moveCard()` in it)

**Comment by SArendeli** [comment]
Okay sounds good, I'll take a shot at it
