### ISSUE TITLE
CotE - Miya Library

### ISSUE THREAD

**Issue by Kwaice** [gryffon/ringteki#2792]
![ml](https://user-images.githubusercontent.com/25953788/51437962-f9f0cc00-1ca5-11e9-946c-5f00fa56fa54.jpg)

**Comment by Matthew-Griffith** [comment]
I'd like to take a stab at this one

**Comment by jeremylarner** [comment]
There are two ways to do this, a easy (or easier) way and a hard way:
1) The hard way is to write a rearrange game action
2) The easier way is to do something like Togashi Mendicant with a prompt to switch a card first.

**Comment by jeremylarner** [comment]
#2831 Might be useful for implementing this card

**Comment by Matthew-Griffith** [comment]
Thanks, I'm at work right now but I will take look at those things plus the discord conversation once I'm home
