### ISSUE TITLE
CotE - Hantei XXXVIII

### ISSUE THREAD

**Issue by jamesoddy** [gryffon/ringteki#2801]
![image](https://user-images.githubusercontent.com/958931/51632353-02b3fd00-1f47-11e9-85e0-d7fe2e4779ac.png)

**Comment by jeremylarner** [comment]
Cards which need reviewing:
Ambush
Azunami
Backhanded Compliment
Court Games
Duelist Training
Favored Niece
Fusui Disciple
Kitsuki Investigator
Policy Debate
Prudent Challenger
Taryu-Jiai
The Perfect Gift
Time For War
Upholding Authority
Utako Kamoko
