### ISSUE TITLE
CotE - Righteous Magistrate

### ISSUE THREAD

**Issue by jamesoddy** [gryffon/ringteki#2803]
![image](https://user-images.githubusercontent.com/958931/51632440-3a22a980-1f47-11e9-871e-a92054c55519.png)

**Comment by Matthew-Griffith** [comment]
hey can I take a shot at this one

**Comment by Matthew-Griffith** [comment]
sorry I actually think I don't want to take this one. I been looking it over and think it would be a lot tougher than I first thought.

**Comment by jeremylarner** [comment]
This one is fairly straightforward - you just need a persistent effect which gives 3 cannot effects to each player:`gainHonor`, `loseHonor`, `takeHonor`

**Comment by Matthew-Griffith** [comment]
Oh okay, I see I can take this one.

**Comment by jamesoddy** [comment]
Take a look at `BorderlandsDefender` and that should get you going.  Combined with the new `AkodoToturi2` you should have everything you need.

**Comment by jamesoddy** [comment]
To be clear you just want the `playerCannot` effect from Toturi not the lasting effect or anything like that.
