### ISSUE TITLE
MotC - Kakita Yuri

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#2901]
![image](https://user-images.githubusercontent.com/31585532/52865689-14975300-3135-11e9-86a5-e33ba9b8db61.png)

**Comment by jamesoddy** [comment]
Something to bear in mind when implementing:

![image](https://user-images.githubusercontent.com/958931/56640583-4cf26a80-666b-11e9-80b3-607dc5178e20.png)
