### ISSUE TITLE
Masters of the Court (12/28 spoiled)

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#2908]
- [ ] #2907 Daimyo's Gunbai 
- [ ] #2906 The Spear Rushes Forth
- [ ] #2905 Market of Kaze-no-Kami
- [ ] #2904 Shinjo Haruko
- [ ] #2903 Daidoji Uji
- [ ] #2902 Kakita Favorite
- [ ] #2901 Kakita Yuri
- [ ] #2900 Kyuden Kakita
- [ ] #2899 Distinguished Dojo
- [ ] #2898 Political Sanctions
- [ ] #2897 Asahina Takimori
- [ ] #2896 Akoto Makoto

**Comment by gryffon** [comment]
Converted to Project
https://github.com/gryffon/ringteki/projects/12
