### ISSUE TITLE
Try Again Tomorrow possible bug

### ISSUE THREAD

**Issue by CDMayberry** [gryffon/ringteki#2910]
> during a battle where i was defending with an honored courtier, wanting to play it on the opponent's attacking character
clicking the card did nothing at all, in the end used manual mode to send it to discard

Wasn't in the match for this one, so not sure. The tests for TAT are excellent, it seems unlikely it was an issue with the card itself. Could just be he tried to use it around the time the servers died. 

I'll try to hunt some of these bugs down tomorrow if it's not resolved sooner.

EDIT: Got a second bug report for TAT, had honored defending courtier, couldn't click on the card.

**Comment by Syrail** [comment]
Just got another report of the same behavior. We may have an edge case where Try Again Tomorrow is not passing a restriction check that it should be.
