### ISSUE TITLE
Honorable Challenger (Pride ?) bug

### ISSUE THREAD

**Issue by Kwaice** [gryffon/ringteki#2917]
After winning a conflict, Honorable Challenger didn't get honored by the Pride keyword.  She won her duel before.

**Comment by IMABUNNEH** [comment]
Same: Honourable challenger (Pride Lion dude) lost her duel, then lost the conflict while defending, did not dishonour.

**Comment by jamesoddy** [comment]
This was an error in the fiveringsdb-data and was fixed in commit https://github.com/Alsciende/fiveringsdb-data/commit/0bc790bf83663f9a0124e251c48f84e6d50e8b0f
