### ISSUE TITLE
Game crashes when putting fate on rings

### ISSUE THREAD

**Issue by naesseth** [gryffon/ringteki#2921]
Game crashed twice now when I've used Master Alchemist or Kitsuki Investigator to add the fate to rings. I drop out of the game immediately and get the red error box:
![image](https://user-images.githubusercontent.com/7195403/52910926-b8504280-329e-11e9-9f43-2e658edb5ad2.png)

**Comment by Syrail** [comment]
Looking at this now. Thanks for the report!
