### ISSUE TITLE
Useless tests?

### ISSUE THREAD

**Issue by IMABUNNEH** [gryffon/ringteki#2925]
Think these tests are a holdover from ThroneTeki? Can't see any purpose for them in the codebase.

test/client/decks/plotValid.json
test/client/decks/plotTooFew.json
 test/client/decks/plotWinter.json
test/client/decks/plotTooMany.json
test/client/decks/plotValidDuplicate.json

**Comment by jeremylarner** [comment]
Yes, probably

**Comment by jamesoddy** [comment]
These were purged in the great cull of 2019 #3263
