### ISSUE TITLE
WotW: Aranat

### ISSUE THREAD

**Issue by Kwaice** [gryffon/ringteki#2954]
![l5c17_card_aranat](https://user-images.githubusercontent.com/25953788/53119987-1310c500-3551-11e9-897f-78253b08a4d1.png)

**Comment by jeremylarner** [comment]
I think the timing is going to be tricky on this one, so I'll take it

**Comment by jamesoddy** [comment]
Oops.  BTW the "Close issue" in the projects page doesn't close the issue popup - it actually closes the issue :/
