### ISSUE TITLE
Fire Tensai Acolyte cannot declare attacks when only character in play

### ISSUE THREAD

**Issue by Syrail** [gryffon/ringteki#2960]
Player reports that when Fire Tensai Acolyte is the only character on the board, its controller is forced to pass conflict declaration, even when the Fire ring is unclaimed.

**Comment by Matthew-Griffith** [comment]
I try to fix this bug

**Comment by Matthew-Griffith** [comment]
I have confirmed the report bug and I found another one. you can also select the fire ring and then the acolyte as an attacker and then change the conflict type and the acolyte is able to start that conflict

![image](https://user-images.githubusercontent.com/22338548/53295265-87ec3500-37c5-11e9-9d72-0b334908543d.png)

**Comment by Citadel97501** [comment]
This issue is still in place, as I have tried to use him a couple times and it keeps on failing.

**Comment by jamesoddy** [comment]
The conflict declaration has just been refactored and deployed as part of MotC that should fix this issue.  If you still have an issue please create a new issue.
