### ISSUE TITLE
Duelist Training cannot be activated

### ISSUE THREAD

**Issue by Syrail** [gryffon/ringteki#2962]
User reports Duelist Training could not be activated in a conflict with two participating characters, both of whom had Military skill. 

Turn sequence 
Court games played by P1 on prodigy of the waves to honor
Court games played by P2 on same to dishonor - cancelled by P1's Defend Your Honor
P1 tried to activate Duelist Training on the prodigy, and was unable.

**Comment by schnalph** [comment]
I had the same issue.  Doji Whisperer attacking political with Hida Kisada defending, attached duelist training to Kisada, Crane buffed Whisperer with Asahina Artisan, could not activate duelist training on Kisada.

**Comment by IMABUNNEH** [comment]
Wre you clicking the attachment or the character? (as DT gives the ability to the character)

**Comment by jamesoddy** [comment]
^^ IMABUNNEH could well be correct, the ability is given to the attached character not on the duelist training card itself.  I'll close this issue as we have no other reports of Duelist training not working.
