### ISSUE TITLE
More than 10 attachments on the same character doesn't work correctly

### ISSUE THREAD

**Issue by naesseth** [gryffon/ringteki#2963]
If you play more than 10 attachments on a character it seems that the stats are added correctly but you can't trigger the abilities of the 11+ attachments. For example I played Talisman as the 11th and I saw the stats increase but couldn't trigger its ability.

**Comment by Syrail** [comment]
I'll look into this. I know I fixed rendering of 10+ attachments but perhaps there was some wiring to gameplay that I missed.

**Comment by lutomlin** [comment]
It's not the gameplay wiring, I hit this today - the 10th attachment is hidden. It shifts the character to the right a little bit to make room for it, but it's just empty space instead of showing the attachment.

**Comment by jamesoddy** [comment]
This should now be fixed and deployed.  Closing issue.
