### ISSUE TITLE
Bayushi's Whisperers not working

### ISSUE THREAD

**Issue by BayushiShimiji** [gryffon/ringteki#2965]
Noticed in a game today that the card named by bayushi's whisperers can still be played. 
I dont know if this is something currently being worked on or not
If not, please look into it?
If so, sorry for bothering you.

**Comment by Matthew-Griffith** [comment]
so I tested this out on a local host of the server and bayushi's whisperers seems to be working

![image](https://user-images.githubusercontent.com/22338548/53306662-fb418580-385d-11e9-9d4a-b72fb2247e64.png)

**Comment by jamesoddy** [comment]
Closing this issue.  If anyone still has problems, please create a new issue.
