### ISSUE TITLE
Yasuki Procurer's effect not working unless it's on the field

### ISSUE THREAD

**Issue by KeitaDragoon** [gryffon/ringteki#2968]
First player, 8 fate. Play Procurer for 2, go to 6 fate. Dishonour Procurer to make the next card to make the next attachment or character I play 1 cheaper. Play Way of the Crab sacing Procurer go to 5 Fate. Attempt to play Kaui Shuichi but can only place 1 fate on him.

Unless I'm missing something in the rules I can still use his action to make Shuichi cost three, meaning with my 5 fate I can play him with 2 fate on the card?

**Comment by jamesoddy** [comment]
Assuming this was still in the Dynasty Phase this was fixed in PR #3132 (and was a general issue with Procurer in the Dynasty Phase).

Thanks for the report!
