### ISSUE TITLE
Connection is not private

### ISSUE THREAD

**Issue by Herudaio** [gryffon/ringteki#2970]
jigoku.online normally uses encryption to protect your information. When Google Chrome tried to connect to jigoku.online this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be jigoku.online, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Google Chrome stopped the connection before any data was exchanged.

You cannot visit jigoku.online right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.

**Comment by Syrail** [comment]
This was caused by certificate expiration and can be safely closed without further action.
