### ISSUE TITLE
WotW: Shosuro Hyobu

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#2981]
![image](https://user-images.githubusercontent.com/31585532/53553137-d63a6480-3b34-11e9-885b-21ad580c34b0.png)
Reaction: After an opponent discards 1 or more cards from his or her hand due to the cost or effect of a card ability, choose a character - dishonor that character

**Comment by TimeZeroX** [comment]
I witnessed a game where Hyobu was able to activate from discarding a duplicate from the provinces.
![Shosuro Hyobu](https://user-images.githubusercontent.com/50306904/57202661-07d90d00-6f76-11e9-9c35-ad908dfce48b.jpg)
