### ISSUE TITLE
I can swim bug

### ISSUE THREAD

**Issue by nicholasalbanese** [gryffon/ringteki#2984]
Hello, 

Today I was playing a game and was unable to use I can swim despite meeting all the conditions. When clicking the card nothing happened. Here is my screen for reference.

![i can swim bug](https://user-images.githubusercontent.com/48135175/53658255-1bca6080-3c0d-11e9-8067-5cd86d8187c7.jpg)

It was my intention to use I Can Swim on Mirumoto Raitsugu. Unless I'm missing something it seems like a bug.

**Comment by jamesoddy** [comment]
A bit difficult to see from your screenshot, but does Raitsugu maybe have Above Question attached?  In which case he could not be targeted by I Can Swim.

And as he is the only dishonored character, there are no eligible targets for I Can Swim so you cannot activate it.

**Comment by nicholasalbanese** [comment]
Oh yes my mistake. I did not notice that. Sorry for the confusion.

**Comment by jamesoddy** [comment]
No problem - keep those reports coming if you spot any problems!

I'll close this issue.
