### ISSUE TITLE
Duelist Training - text output is not clear in some situations

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#2993]
If Kakita Kaezin (for example) has duelist training and then uses it's action to duel, nothing in the output indicates that he is using the duelist training action instead of his own printed action. 

![image](https://user-images.githubusercontent.com/32277970/53758846-e338ba00-3e8c-11e9-9501-7542b2b8f499.png)

**Comment by jamesoddy** [comment]
This was addressed in #3271
