### ISSUE TITLE
Help required with Decks not loading.

### ISSUE THREAD

**Issue by ideyesugei** [gryffon/ringteki#3006]
I an finding that I can not load my decks from the server. If I launch into a new tab it shows the title and invalid until I click on the deck adn then it loads the contents. I have one deck 'FFS tester' which shows as invalid and will not let me delete it.

**Comment by jamesoddy** [comment]
Hi,

Apologies we have not responded sooner.  It would be great if you could provide us with some screenshots detailing the problem.

**Comment by jamesoddy** [comment]
No further response
@ideyesugei If you still have this issue please open a new issue
