### ISSUE TITLE
Graphical Bug - Usernames hyperlinked as cards

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#3010]
Not at all crippling, but a bit strange.

![image](https://user-images.githubusercontent.com/32277970/54205970-c5331100-44ad-11e9-96b8-d3e553f37e16.png)

**Comment by jamesoddy** [comment]
This has been around a while, but like you said, was pretty minor so we hadn't got round to fixing it.  I've submitted a fix.
