### ISSUE TITLE
WotW: Moto Chagatai

### ISSUE THREAD

**Issue by Kwaice** [gryffon/ringteki#3019]
![image](https://user-images.githubusercontent.com/25953788/55096906-1270ce80-50bb-11e9-9cc3-4d369ec61cd7.png)

**Comment by Matthew-Griffith** [comment]
hey could I take this one?

**Comment by Kwaice** [comment]
Sure go ahead :D

**Comment by Kwaice** [comment]
Might be interesting for your tests : 

"Moto Chagatai only ignores the framework bow that occurs during step 3.2.8 Return Home."
