### ISSUE TITLE
Bustling Academy

### ISSUE THREAD

**Issue by thimacek** [gryffon/ringteki#3021]
Hi folks, thanks for all your work!

It seems like Bustling Academy cannot be played even when you control a Scholar right now. I also tried a workaround with manual mode, but I couldn't get a new dynasty card to be attached face down to a province after discarding a card.

I've just noticed the last topic about this card is quite old. Maybe it was working before and something got changed along the way?

Thanks again!

**Comment by Kwaice** [comment]
I can't replicate this, it seems to work fine.

Can you please submit a screenshot if you encounter this problem again ?
