### ISSUE TITLE
Unveiled Destiny not working when ring is claimed

### ISSUE THREAD

**Issue by Shadow77113** [gryffon/ringteki#3032]
Hey all, thanks for your hard work on Jigoku, really appreciate it. Ran into a bug earlier today, was playing SoW, my opponent already had claimed the water ring and on my next attack I wanted to resolve the water ring with Unveiled Destiny but I could not click on the water ring to resolve.

**Comment by Matthew-Griffith** [comment]
so I test this one both writing a test to play out the conditions you had above and tested it in the actual game. the card seem to work but you have to click the ring which get moves to above slash below the players honor dial. 

![Screenshot from 2019-04-19 19-09-24](https://user-images.githubusercontent.com/22338548/56447632-8166cf00-62d7-11e9-9a7b-675f0d5b90e1.png)
![Screenshot from 2019-04-19 19-10-24](https://user-images.githubusercontent.com/22338548/56447635-83309280-62d7-11e9-9c8a-3c653eef2272.png)

the first screenshot is after winning the conflict and I am prompt to choose a ring and it looks like I can only select the fire ring but I click the air ring above my honor dial and got the 2nd screenshot.

**Comment by jamesoddy** [comment]
Yeah, you have to click the ring in the ring in the claimed area.  This is a common issue people have so we are working on a better way to resolve "choose a ring" effects in PR #3153

I will close this issue as it does not look like it is a bug (if you are still having issues please create a new issue).
