### ISSUE TITLE
Kirei-Ko timing is not updated for most recent rules update

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#3033]
A couple examples.
If I have 1 fate, and my opponent plays Goblin Sneak to steal my fate, I should not be able to react with Kirei-Ko.  The fate should be gone by that point.
If my opponent activates the CotE Toturi, I shouldn't be able to react with Kirei-Ko, because it isn't legal anymore since Toturi's action prevents it.

**Comment by jamesoddy** [comment]
This is now active
