### ISSUE TITLE
Loyal Challenger interaction when "stolen" via Shosuro Actress Bug

### ISSUE THREAD

**Issue by ruudoniac** [gryffon/ringteki#3040]
Loyal Challenger's passive ability triggers as if my opponent controls it , although i have her under my control via Shosuro Actress (ex I win the conflict with her and he loses honor instead of me getting honor), guess same stands for Blackmail , not tested that though.

**Comment by jamesoddy** [comment]
Confirmed and fixed in PR #3154

Thanks for the report!
