### ISSUE TITLE
unexpected interaction between Akodo Toshiro and Shinjo Ambusher

### ISSUE THREAD

**Issue by tbyswinson** [gryffon/ringteki#3042]
I have tested with my friend. If I use Akodo Toshiro's action ability first, then my Shinjo Ambusher cannot trigger the reaction ability. However, if I use the reaction ability of Shinjo Ambusher first, the province will break even I trigger Akodo Toshiro's action ability after.

**Comment by jamesoddy** [comment]
@tbyswinson Thanks for the report.

Confirmed that this happening with a test, just need to find out what's going on now :)
