### ISSUE TITLE
MotC - Bayushi Dairu

### ISSUE THREAD

**Issue by Matthew-Griffith** [gryffon/ringteki#3050]
![image](https://user-images.githubusercontent.com/22338548/56476994-4519a700-646e-11e9-80ce-caa15b205217.png)

**Comment by TimeZeroX** [comment]
Even though he was participating in a conflict, I couldn't activate his ability.

**Comment by Matthew-Griffith** [comment]
The code for this card isn't on jigoku yet. Once the rest of the pack is out he will work.
