### ISSUE TITLE
If you accidentally pass a conflict

### ISSUE THREAD

**Issue by etaywah** [gryffon/ringteki#307]
Currently you must manually do the conflict. Not too difficult with current coding. Maybe a manual /declare conflict?

**Comment by YogoGohei** [comment]
I can't speak for the OP, but I would think an extra "are you sure?" with a button that says "Skip conflict" instead of "Pass" would be enough to resolve this.  

This would interrupt the normal flow just enough to snap people out of autopilot.

**Comment by jeremylarner** [comment]
Hmm, interesting idea.  My only concern is that I already have people complaining that they have to click pass too many times as it is. Passing a conflict does seem like a fairly major decision though.  

I don't really want to add a /declare-conflict because it could cause gamestate issues. The other solution I'm thinking about is adding a chat command to give both players an additional conflict opportunity.  So if you pass by accident, you can use that command and ask your opponent to pass as well.

**Comment by YogoGohei** [comment]
My argument for my approach is that, as you say, skipping a conflict is a pretty big deal.  It doesn't happen too often and if you are doing it, you want to be sure you meant to do it.

I work as a software developer (sadly I am not good with javascript, or I would help with the coding) and it's amazing how much an extra prompt, when none was expected, can get someone to actually read the damn thing.

**Comment by jeremylarner** [comment]
Yes, I can definitely see where you're coming from. 

My concern is the case where the first conflict of the round happens to be a huge fight, and at the end of it everyone is bowed.  I've had complaints that you then need to click through passing three conflicts and all the action windows in between, and then action windows in the fate and regroup phase before something happens again.

**Comment by YogoGohei** [comment]
hmmmm... good point.

How much danger is there in having it automatically skip your conflict opportunity if you don't have anyone that can legally partake in it?

**Comment by YogoGohei** [comment]
I am probably being really obnoxious on this, and if so you can tell me to pipe down...
But...
After playing a bunch more games, I think that simply changing the button text from "Pass" to "Skip Conflict" with no further changes will fix this problem in 95% of cases.

Just a suggestion.

**Comment by jeremylarner** [comment]
I went with 'Pass Conflict' - open to more feedback on this issue down the line

**Comment by Arbuzio** [comment]
I think it is definitely worth it just to re-word button 'pass' that passes conflict to 'Skip First Conflict' and 'Skip Second Conflict'.

For a newbie it is a very common case to forget which conflict they are currently.

**Comment by jeremylarner** [comment]
I've added an 'Are you sure?' prompt to passing a conflict #736
