### ISSUE TITLE
Khan's Ordu

### ISSUE THREAD

**Issue by Kradlo** [gryffon/ringteki#3081]
Khan's Ordu does not switch the conflict type to military.

**Comment by WhiteOnmyoji** [comment]
Confirm this happens. 
![image](https://user-images.githubusercontent.com/34945187/56800940-74515f00-6846-11e9-9b24-10784cb698ff.png)

**Comment by jamesoddy** [comment]
@WhiteOnmyoji Thanks for the screenshot and confirmation - they are very helpful.  This has been fixed in #3080 and should be deployed to jigoku soon.
