### ISSUE TITLE
Daidoji Uji does not work

### ISSUE THREAD

**Issue by Kradlo** [gryffon/ringteki#3101]
When Daidoji Uji is honored, you should be able to play characters from your provinces as if they were in your hand and reduced in cost by 1 fate.  Currently unable to play characters from the provinces at all.

**Comment by Kwaice** [comment]
The Crane pack is not yet available on Jigoku.

**Comment by Kradlo** [comment]
Odd, because I was able to upload a deck with Masters of the Court to
Jigoku and play a game with it.

**Comment by Kwaice** [comment]
Yes, the data is already pulled from FiveringsDb but the cards are not implemented yet.
