### ISSUE TITLE
Daimyo's Gumbai fetches image for Retreat

### ISSUE THREAD

**Issue by IMABUNNEH** [gryffon/ringteki#3130]
I know Crane pack isn't functionally implemented yet, but just a heads up, currently Gumbai calls the image for Retreat in game. Can still attach it to a character and it still counts the +2/+2, but it shows as Retreat.

Assuming this will be fixed when Crane implemented, but in case you needed to point to the right image.

**Comment by jamesoddy** [comment]
This is fixed now
