### ISSUE TITLE
Web of lyes

### ISSUE THREAD

**Issue by Wacos77** [gryffon/ringteki#3180]
My scorp opponent bid 1 on his honor bid but his Web of Lyes province has 10 strenght, i think its a bug

**Comment by The-Outcast** [comment]
Hi, thank you for reporting this issue.

Please take into account that we require as much context as possible as developers to be to reproduce possible issues. The main thing that can help us with this is providing a screenshot of the game so we can determine more easily what is possibly happening.

At the moment all our tests for Web of Lies are still pointing it should be working correctly and local testing has supported that fact.

As some additional information do note that Web of Lies' power can change outside of the draw phase bid by something like a duel. The Opponents dial can change to a higher number then and increase Web of Lies' province strength.

I have noted though that the chat doesn't seem to make clear a province is breaking until the attacker takes an action. We will see if we can make this more clear.

Regards,

the-outcast.

**Comment by Wacos77** [comment]
My opponent bid was 1 when i attacked web of lies. Maybe the problem was
only on the chat since i was checking the broking message and it wasnt
there unti i made an action to surpass 10 strength.

Il sab 11 mag 2019, 03:33 Tom Nys <notifications@github.com> ha scritto:
