### ISSUE TITLE
Fix display of fate count for rings

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#32]
We have the ability to track fate on ring tokens, however, it ends up centering the display of said tokens, so it's not currently useful for an actual count.

This can be seen in-game by using the /add-fate-ring command, eg; /add-fate-ring air 1

**Comment by jeremylarner** [comment]
I've got a branch which fixes this and also makes a nicer looking fate counter using the fate counter image.

**Comment by gryffon** [comment]
This has been resolved.
