### ISSUE TITLE
FtE Card #8 : Magistrate of Reason

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#3235]
![fte8](https://user-images.githubusercontent.com/6053185/58710625-c11adf00-838a-11e9-90ae-f55c1cf34885.png)

**Comment by jamesoddy** [comment]
Waiting on ruling for timing of the additional cost

**Comment by TimeZeroX** [comment]
This is the same timing as any other cost:
![image](https://user-images.githubusercontent.com/50306904/59569260-c21f6200-9054-11e9-948d-ca4d013b57da.png)
