### ISSUE TITLE
FtE Card #15 : Moment of Perfect Beauty

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#3238]
![fte15](https://user-images.githubusercontent.com/6053185/58711167-e52af000-838b-11e9-919d-731267ae9386.png)

**Comment by Matthew-Griffith** [comment]
I'll take this one

**Comment by jeremylarner** [comment]
This one is also hard. I would do it by adding a player effect, and then checking for it in the Action window

**Comment by ngroover** [comment]
I can try taking this one.

**Comment by jamesoddy** [comment]
Waiting on ruling regarding this vs. Hawk Tattoo
