### ISSUE TITLE
FtE Card #18 : Command Respect

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#3241]
![fte18](https://user-images.githubusercontent.com/6053185/58711525-b6f9e000-838c-11e9-9d91-369d18876afb.png)

**Comment by Matthew-Griffith** [comment]
I'll take this one

**Comment by jeremylarner** [comment]
This one is difficult, because there's no way currently to add costs to an ability.  I'm not sure whether the honor needs to be paid before the event is played, or with other event costs....

**Comment by Matthew-Griffith** [comment]
My thought was that I could write a gameaction like `cardLastingEffect` but have have it work like a forced reaction

**Comment by jamesoddy** [comment]
Waiting on ruling on timing of the additional cost

**Comment by TimeZeroX** [comment]
The costs to be paid all happen at the same time as per the Rule Reference:
