### ISSUE TITLE
Trade on the Sand Road

### ISSUE THREAD

**Issue by XavierMurphy** [gryffon/ringteki#3246]
I could not use my opponent's removed cards.

**Comment by jamesoddy** [comment]
Can you please provide a screenshot of the game?  I'm afraid that this isn't enough to go on to look into a potential issue as we have not had any other reports of problems with TotSR (at least recently 😉 ).

**Comment by XavierMurphy** [comment]
Hi,

I did not think on that when it happened. I will do next time if it reoccurs. Thanks.
________________________________
De: James Oddy <notifications@github.com>
Enviado: lunes, 3 de junio de 2019 19:09
Para: gryffon/ringteki
Cc: XavierMurphy; Author
Asunto: Re: [gryffon/ringteki] Trade on the Sand Road (#3246)


Can you please provide a screenshot of the game? I'm afraid that this isn't enough to go on to look into a potential issue as we have not had any other reports of problems with TotSR (at least recently 😉 ).

**Comment by jamesoddy** [comment]
Thank you for the follow up.  I will close this issue - please open up a new one if you manage to get a screenshot of the issue in the future.
