### ISSUE TITLE
BoB - Forebearer's Echoes #39

### ISSUE THREAD

**Issue by jamesoddy** [gryffon/ringteki#3305]
![image](https://user-images.githubusercontent.com/958931/60576127-b5994a00-9d74-11e9-8b62-c65ba8451433.png)

**Comment by jeremylarner** [comment]
Need to check this interacts correctly with 'immune to events' effects (i.e. if you bring a character into play, and then it becomes immune to events, it shouldn't go to the bottom of the dynasty deck)
