### ISSUE TITLE
Hida Guardian - no bonus / +0 +0

### ISSUE THREAD

**Issue by TripleTex86** [gryffon/ringteki#3310]
ATM Hida Guardian only grants +0 +0 even if there is a elegible holding in play.

**Comment by jwittenbach** [comment]
Can confirm -- happened to me today as well. Using the hover stats on the targeted character, I could see a line in both military and political strength saying something to the effect of "Hida Guardian buff: +0" even though I clearly had a holding in play at the time.

**Comment by jamesoddy** [comment]
This is fixed by #3302 which should hopefully be deployed soon.

Thanks for the report! (screenshots are helpful for any future reports)
