### ISSUE TITLE
Conflict totals not adding up properly.

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#336]
Was playing the game earlier and the conflict counts were wrong in a way that I couldn't explain.
It's a bit hard to see form the image, but one side has a seppun guardsman with a fine kitana.  The other side has no one.  No one has the favor.

Conflict total? 4-1... somehow.

Immediately before this point the crab player had a Kaiu Envoy in play with a Fine Kitana attached.  That character was thrown on the Funeral Pyre when it became clear that the Crab couldn't win the conflict.  I suspect the game didn't re-arrange the conflict values properly when that character left play.

![image](https://user-images.githubusercontent.com/32277970/31350879-cbd77df2-acf6-11e7-92a3-4a4ceec0c91b.png)

**Comment by jeremylarner** [comment]
I think there is already a fix for this submitted in #304 

Thanks for the report though - I particularly appreciate the screenshot and the detailed explanation of the problem!
