### ISSUE TITLE
JfS - Isawa Heiko

### ISSUE THREAD

**Issue by jamesoddy** [gryffon/ringteki#3379]
![image](https://user-images.githubusercontent.com/958931/62148849-694d1580-b2f2-11e9-9e78-79b2819c03c1.png)

**Comment by Matthew-Griffith** [comment]
I'll take this one

**Comment by jamesoddy** [comment]
![image](https://user-images.githubusercontent.com/958931/62698322-c4f35f00-b9d4-11e9-9e1a-10469be27c82.png)

Correct text :)
