### ISSUE TITLE
Tactician's Apprentice / Contingency Plan

### ISSUE THREAD

**Issue by shadowpuppet117** [gryffon/ringteki#3429]
Both of these cards work on when revealed and should be able to have the dial lowered with contingency plan and then have the apprentice draw a card. 
![Capture](https://user-images.githubusercontent.com/54815228/64128666-9f643600-cd85-11e9-93ca-0119bcb38013.PNG)

**Comment by The-Outcast** [comment]
![image](https://user-images.githubusercontent.com/50174301/64527197-97684100-d305-11e9-8696-e20ed84479b4.png)
When something refers to the honor bid, it is refering to value on the dial, not any modified values. And seeing as that mail is from January, We are going to go by RRG and say this doesn't work.
