### ISSUE TITLE
Popup windows for decks are wrongly positioned and shaped

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#37]
If you click on 'Show' in the menu of either Conflict or Dynasty deck, the resulting Popup window is positioned below the deck (instead of above it) and it's laid out as a 1 by the number of cards in the deck.

**Comment by gryffon** [comment]
Yeah, that most likely means that a class isn't showing right. The province
deck was doing the same thing, but I managed to find the issue.

Something is probably wrong in the css.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by jeremylarner** [comment]
Thanks for pointing me in the right direction - CSS was a complete mystery to me before this

I've submitted a fix for this also
