### ISSUE TITLE
Chat breaks as soon as you put a card into play

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#39]
Dragging a card into play from your hand or either deck, or completing setup and clicking a card in a province breaks the chat box, and stops players sending messages, or game generated messages from appearing.

**Comment by jeremylarner** [comment]
Fix submitted

**Comment by gryffon** [comment]
Put into play works. There seems to be a couple more instances, mostly related to chat commands which break it as well.

**Comment by jeremylarner** [comment]
Most of the time where I see this problem it's due to the game passing a BaseCard (or DrawCard) object to chat directly.  The chat message code deals well with player objects, but not card objects, so I think the best fix is to add code which replaces BaseCard with its name.
