### ISSUE TITLE
Please fast track certain cards

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#421]
There are several cards that cannot be played correctly given the current interface just using manual commands.  These include any cards that put things on the bottom of your deck, and anything that searches the top x cards of your deck for a card. 

There may be others, but the cards that I have encountered are:
Kitsu Spiritcaller
Secret Cache
Agasha Swordsmith

I did notice that Shrewd Yasuki, who both searches and puts stuff on the bottom, is implemented.  Which is great!

**Comment by jeremylarner** [comment]
Those should all be implemented now - please let me know if they aren't working

**Comment by jeremylarner** [comment]
The only card of that type which isn't implemented is Artisan Academy, and I'm working on it now
