### ISSUE TITLE
Shosuro Actress Bug

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#427]
I attempted to use Shosuro Actress to bring in my opponent's Isawa Masahiro.
My opponent controlled a Isawa Masahiro at the time.
It wouldn't let me do it, possibly due to a bug in how uniqueness is implemented?  He also couldn't drag his Isawa Masahiro out of the discard to use /give-control, also due to uniquness.

**Comment by jeremylarner** [comment]
Thanks for the report - you're right the code is still using AGoT uniqueness rules (the play you made wouldn't be allowed in thrones). Fix submitted
