### ISSUE TITLE
Uniqueness isn't being applied to cards correctly

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#44]
While cards seem to be pulling most keywords correctly from the database, unique doesn't work.
It might be because it's called unicity or something?

**Comment by gryffon** [comment]
I don't think there is any code for the unique effect yet. The current goal
is to just get the game playable as a surface. Willing to let some things
be manual until then. Then at that step, start making sure the rest of the
rules are put in place.

**Comment by alex-whitney** [comment]
[`Player.putIntoPlay`](https://github.com/gryffon/ringteki/blob/master/server/game/player.js#L506) will restrict you from putting a unique card into play if you already control or own a unique card that is in play. There are also [working tests](https://github.com/gryffon/ringteki/blob/master/test/server/player/putintoplay.spec.js#L32) for these scenarios.

It looks like `is_unique` was renamed `unicity` in `fiverings-db`. It should be a pretty quick change here:
https://github.com/gryffon/ringteki/blob/640836b1b6df527cae37b81b4ea06ca4f454de65/server/game/basecard.js#L350-L352

**Comment by jeremylarner** [comment]
Sorry, I wasn't very clear.  The code does check for uniqueness, and my code also allows you to discard duplicates to add fate to cards in play.  However, the cards themselves all return 'undefined' from isUnique().  They seem to give the correct values for Limited, Ancestral and other keywords, so I guess that the script which assigns the card data structure values from the database is not doing this one right.
