### ISSUE TITLE
Way of the Phoenix + reactions

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#456]
In the "Do you want to react" prompt that pops up after your opponent plays way of the phoenix, the ring that they selected is not indicated.  The selected ring does not appear in the chat until after you have chosen to not react.

Whether or not you want to react (Voice of Honor, Forged Edict, etc.) depends heavily on what ring they picked, and currently the only way to know that is to ask the opponent.

**Comment by YogoGohei** [comment]
Rumormonger + ring of fire has the same issue.  The dialog just tells you they are resolving the ring, not whether they are honoring / dishonoring or who they intend to target, prior to being prompted to use the Rumormonger.

**Comment by jeremylarner** [comment]
The rumormonger thing should have been fixed in #646.
Still working on targeting prompt changes for WotP

**Comment by jeremylarner** [comment]
A related Young Rumormonger bug.  If Shameful Display is triggered, the game prompts you to trigger rumormonger for the honor effect, but not the dishonor one

**Comment by jeremylarner** [comment]
Rumormonger bug fixed in #739.
Still working on targeting controls for WotP

**Comment by jeremylarner** [comment]
targeting controls added for WotP (and Court Games) in #773
