### ISSUE TITLE
Game seems to hang when a second tab (help or chat) is opened

### ISSUE THREAD

**Issue by tobinlopes** [gryffon/ringteki#473]
Hey folks,

We tried to play tonight and noticed that when I opened up the Help or Chat in another tab on Chrome, while playing a game, the game froze. No chat, prompts, etc. 

Otherwise, the site seems in a good place for this early in its development.  

Thanks,
Tobin
-tpl

**Comment by jeremylarner** [comment]
Hmmm, interesting.  I was able to reproduce this.  Not sure what we can do about it.  As a workaround, the game will work fine if you play it in the second tab, and use the first to go to About/How To Play/whatever.  But yes, the game won't work in the first tab any more
