### ISSUE TITLE
Rout and Honored

### ISSUE THREAD

**Issue by Kwaice** [gryffon/ringteki#553]
Hello,

Thanks for the hard work, the platform is looking great. I love playing on it.

I noticed a bug during a conflict.

I played Rout to send Shinjo Tatsuo home. My attacking character was an Honored Akodo Gunsô (4 military strength) and Shinjo Tatsuo had 3 military strength. 

But rout wouldn't let me target Shinjo Tatsuo somehow.

![screen shot 10-18-17 at 02 00 pm](https://user-images.githubusercontent.com/25953788/31717557-bf8376b0-b40c-11e7-9c67-df1e789039ad.PNG)

**Comment by jeremylarner** [comment]
Hmm, I don't seem to be able to replicate this.  I tried setting up the scenario as you described it, but Rout seems to be targeting correctly for me.

Is there any other circumstances which might be relevant?

It's also possible that the bug has been fixed by general targeting changes I've made to the code recently

**Comment by Kwaice** [comment]
Mmm i moved Shinjo Tatsuo and Border Rider in the conflict just before that i believe. I'll try to replicate the scenario.

**Comment by Kwaice** [comment]
It's maybe related to Akodo Gunsô. 

In this case, i have him honored with a Fine Katana and an Honored Blade in a military conflict (so 4 + 2 + 2 strenght), and i can't Rout a defending 2 military strength Border Rider or Warrior Poet. It's not even launching the skill.

Maybe Akodo Gunsô is not considered a Bushi ?
![screen shot 10-18-17 at 03 04 pm](https://user-images.githubusercontent.com/25953788/31720114-ef2c5a0e-b415-11e7-95a1-bd17fc61c536.PNG)

**Comment by jeremylarner** [comment]
I appreciate the extra work you've done in trying to track down the bug.  When I try to replicate it though, I can use Rout with only an honored Gunso on my side.

Can you give me a series of steps to make it bug?  It's difficult for me to fix if I can't replicate it...

**Comment by Kwaice** [comment]
![screen shot 10-18-17 at 04 35 pm](https://user-images.githubusercontent.com/25953788/31724568-69f04d02-b422-11e7-984e-2cf9d1b07d48.PNG)

In this case: 

(Manually honored Akodo Gunsô before)
During a military conflict between Gunsô and Warrior Poet,

1) I attach a fine katana to honored Gunsô (bringing him to 6)
2) opponent pass for the test
3) I attach honored blade to honored Gunsô (bringing him to 8)
4) Opponent uses Charge to bring Moto Horde (6 strength) in the conflict
5) I want to Rout the Moto Horde with Gunsô (8 to 6, should work) but as you can see in the screenshot, the Horde is not targetable, only the Warrior Poet.

**Comment by jeremylarner** [comment]
Thanks for this - I've rewritten rout, and it seems to work properly now.  Please let me know if you're still seeing any problems #570

**Comment by Kwaice** [comment]
I think you will have to rewrite Outwit too because i run into the same problem, can't Outwit a 2 political character with my 5 political courtier.
