### ISSUE TITLE
Shiba Tsukune Interrupt - Order of Execution Control Bug

### ISSUE THREAD

**Issue by ghodamus** [gryffon/ringteki#573]
Noticed this during a game where both of us happened to be playing as Shiba Tsukune. At the end of the conflict round, her interrupt ability triggers correctly, and the controlling character is prompted to choose which two unclaimed rings to execute. However, it then falls to the first player (regardless of whether they are the controlling player) to choose which of the two rings to execute first. This behavior was observed both when there was a single Tsukune on the field controlled by the second player, and when both players had Tsukune's on the field (in this instance, both Tsukune's triggered, with the first player's card triggering first, but the first player was still prompted for order of execution for the second player's Tsukune).

**Comment by jeremylarner** [comment]
This is the way it's supposed to work according to the developers at FFG.  Both rings resolve simultaneously, and the first player always chooses the order of simultaneous effects where it matters.
