### ISSUE TITLE
Request: More visible indicators for characters in a conflict

### ISSUE THREAD

**Issue by AKWolff037** [gryffon/ringteki#589]
Right now it's very difficult to determine which characters are currently participating in a conflict, could we get a wider outline for the characters that are currently participating?  I thought a red border indicated participation, but there's been multiple times now where characters with either blue or no borders were participating in a challenge and I wasn't aware until they used their abilities and it was too late.

**Comment by jeremylarner** [comment]
A red border does indicate participation, but characters who are not participating are also able to use their abilities.  Unlike the old CCG, the new LCG doesn't require presence to use abilities in conflicts.
