### ISSUE TITLE
Additional fate on character limited by 3

### ISSUE THREAD

**Issue by vmironovich** [gryffon/ringteki#599]
When playing a character the additional fate prompt is limited to [0..3] fate, while the rule is that you can put as much as you want.

> The player then has the option to place any number of additional fate from his or her fate pool onto that character.

**Comment by jeremylarner** [comment]
Yes, this is true, but I didn't want to make the prompt go up to 10 or 12 because that seems silly.  Do you find yourself in boardstates where you want to add 4? or 6? I need to cap it at some point just for the ui.

Note you can always add fate yourself using chat commands.  The other solution I'm looking at is being able to drag fate from your pool onto cards.  Would that be a sufficient way of implementing it?

**Comment by vmironovich** [comment]
I'm pretty sure that in general 0 to 3 is good enough. This problem came up when I was testing cards, but during general gameplay my guess that it's fine as is.

Not sure which way to go. Dragging fate seems fine, but my idea would be to have some kind of "+/-" dialog where you can manually select the amount of fate to put on character. It allows for all values, but takes more time, so not sure.

**Comment by jeremylarner** [comment]
I think pressing a single button is easier than fiddling with +/- buttons, and it would require implementing an entirely new prompt. I can see an argument for going up to 4, but I really think that the amount of game states where you'd ever want more than 4 is very very small.

Any one else want to chip in?

**Comment by Arbuzio** [comment]
Well, if there is no option at all to put 4 fate tokens - it could ruin some games.

Buttons for 0-3 are great, but is it hard to implement input window (under button '3' for example) where you can input with keyboard number of fate tokens?

**Comment by Athosity** [comment]
I agree that 0 to 3 is fairly practical. But i wouldn’t mind manually typing in a number to a dialog box. I would imagine it would be less prone to erroneously choosing how much fate to put also.

**Comment by jeremylarner** [comment]
My current thinking with regard to this is that this may be another thing I let players choose themselves.  I could add an option to the settings menu, and then individual players can choose whether they want fate menus to go up to 3 or 4 or 6 or 10.

**Comment by YogoGohei** [comment]
You could include a "more" button at the bottom and, if clicked, expand the list up to some unreasonably high number (10?)

**Comment by jeremylarner** [comment]
That's an interesting idea - not sure how feasible it is technically.  I'll try and do it and see if it works

**Comment by jeremylarner** [comment]
Added in #753
