### ISSUE TITLE
jigoku.online is down

### ISSUE THREAD

**Issue by carlmiller307** [gryffon/ringteki#6]
When trying to access jigoku.online, I get a DreamHost error page with the following text:

# Site Not Found

Well, this is awkward. The site you're looking for is not here.

Is this your site? Get more info or contact support.

**Comment by elstob** [comment]
@gryffon is still doing preliminary work on the game engine to get it ready for launch. I wouldn't expect that site to be up and hosting Ringteki for a little while yet. 😬

**Comment by gryffon** [comment]
This is correct. The site hasn't gone live yet. It's nearing, but not quite ready for the beta release.
