### ISSUE TITLE
Favored Mount doesn't provide cavalry trait

### ISSUE THREAD

**Issue by vmironovich** [gryffon/ringteki#604]
Favored Mount doesn't seem to provide cavalry trait to attached character. 

I was going to test Let Go interaction with Favored Mount and Born in War, but couldn't attach Born in War to character with Favored Mount attached. Unicorn stronghold does not work in regard to Favored Mount too, as I was unable to use it to move the character into ongoing military conflict.

With cavalry unit in play, it is the only highlighted target for Unicorn stronghold and Born in War targeting.

**Comment by jeremylarner** [comment]
Thanks for the report an replication steps, that was really helpful.
Fix submitted #605
