### ISSUE TITLE
Action window turn order during Conflict Phase seems wrong

### ISSUE THREAD

**Issue by lufia22** [gryffon/ringteki#611]
It's my understanding that in every action window the first player is able to use a card first. The only exception to this is during the action resolution window, in which the defender gets to play first.

I have noticed that the "in-between" action windows in the conflict phase (NOT the action window that occurs during conflict resolution) sometimes lets the second player go first during the action window.

**Comment by jeremylarner** [comment]
Hi, thanks for the report.  You are right, the code on the server is bugged - I submitted a fix for this already (#579) which should be migrated to the server very shortly (if it hasn't been done already)
