### ISSUE TITLE
Matsu Beiona

### ISSUE THREAD

**Issue by Kwaice** [gryffon/ringteki#616]
Currently, Matsu Beiona's reaction only triggers if there is 3 bushi characters on the table before she enters.

Yet i think that there only needs 2 Bushi characters in play for her reaction to trigger, since her reaction triggers after she enters and she counts as a Bushi character too.

**Comment by jeremylarner** [comment]
Her text says: ;Reaction: After this character enters play, if you control 3 or more **other** Bushi characters – place 2 fate on this character.'

**Comment by Kwaice** [comment]
Ah right ! Sorry for that !
