### ISSUE TITLE
Blackmail Artist can be triggered after winning military conflict

### ISSUE THREAD

**Issue by vmironovich** [gryffon/ringteki#624]
`afterConflict: event => event.conflict.isParticipating(this) && event.conflict.winner === this.controller && this.controller.opponent` should also have `event.conflict.conflictType==='political'`.

Sorry I am unable to contribute directly, as I am unable to set up testing environment currently.

**Comment by jeremylarner** [comment]
Thanks for the report - really appreciate your hard work testing!
Fix submitted #627
