### ISSUE TITLE
Indomitable Will does not have a check for winning a conflict

### ISSUE THREAD

**Issue by vmironovich** [gryffon/ringteki#625]
Indomitable Will should be able to be triggered only after winning the conflict. In my game it was triggered after 0 strength tie (no winners) and attacker didn't bow as a result.

`afterConflict: event => (event.conflict.attackingPlayer === this.controller && event.conflict.attackers.length === 1) || (event.conflict.defendingPlayer === this.controller && event.conflict.defenders.length === 1)` should also check that controller won the conflict.

**Comment by jeremylarner** [comment]
Thanks for the report! - Fix submitted #628
