### ISSUE TITLE
"Borderlands Defender" or "The Mountain doesn't Fall" bug

### ISSUE THREAD

**Issue by Kwaice** [gryffon/ringteki#626]
Borderlands Defender didn't bow after successfully defending a conflict.

I used "The Mountain Doesn't Fall" on her the round before but she seemed to keep the buff during the next round, not bowing after each conflict on defense.

**Comment by jeremylarner** [comment]
Hmmm, I can't replicate this.  However, I have a feeling it might be another symptom of the Kisada bug.  Had you're opponent played Banzai and resolved it twice this game?  Did you have a message about an inconsistent game state?

**Comment by Athosity** [comment]
I saw this as well. Borderlands Defender doesn’t bow after participating as a defender.

**Comment by Kwaice** [comment]
Thanks for looking into that.

Yes indeed i had a message about an inconsistent game state after Banzaï was resolved twice..

Opponent also played Way of the Unicorn at the start of the round.

**Comment by jeremylarner** [comment]
Yes, I think this is a follow-on from a double Banzai.  After that, Banzai is left on the ability stack, and Borderlands defender will think that it's trying to bow it for the rest of the game, so it won't get bowed.
