### ISSUE TITLE
Doomed Shugenja allows to put fate while is played from province

### ISSUE THREAD

**Issue by Arbuzio** [gryffon/ringteki#631]
Subj

**Comment by jeremylarner** [comment]
Yes, this is a known issue.  There are three cards which are only partially implemented at the moment, and this is one of them.

**Comment by vmironovich** [comment]
Might I suggest, *as a temporary fix*, returning all fate on Doomed Shugenja played from province back to player?

**Comment by jeremylarner** [comment]
Doomed Shugenja is fully implemented now #648
