### ISSUE TITLE
Way of the Crab...Opponent Sac my character

### ISSUE THREAD

**Issue by HidaWaits** [gryffon/ringteki#637]
Playing in a game today, I used Way of the Crab to sac on of my crab characters, my opponent responded my Sac'ing one of my characters.

"When a player is instructed to sacrifice a card, that player must select a card in play that he or she controls and that matches the requirements of the sacrifice, and place it in his or her discard pile."

Clearly this is not how sacrificing works...a player can only sac cards they control.

**Comment by jeremylarner** [comment]
Yes, this is a known issue. Fix has been submitted #610 

Thanks for the report

**Comment by HidaWaits** [comment]
Thank you!
