### ISSUE TITLE
Young Rumormonger with Shameful Display

### ISSUE THREAD

**Issue by vmironovich** [gryffon/ringteki#644]
Young Rumormonger interrupt prompt does not state which kind of action (honor/dishonor) and the original target of the action it has an option to be triggered off. 

It is relevant with Shameful Display, which triggers dishonor/honor simultaneously, thus you have an interrupt prompt with two "Honor/dishonor a different character" options.

**Comment by jeremylarner** [comment]
Thanks for the report - fix submitted #646
