### ISSUE TITLE
blackmail artist bugs

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#661]
1) The prompt to use him comes up if he wins a military conflict.
2) His ability either isn't working at all, or only partially works.  Text appears in the chat log indicating that he stole an honor, but it doesn't look like the honor exchange actually occurs.  Because I wasn't paying as much attention as I should have been, I am not sure if I gained the stolen honor, but I know for a fact my opponent didn't lose it.

Edit: Reading through other bug reports, the conflicts in question all involved the air ring.  So, maybe there is a bug with how these two cards interact?  In my case I was trying to steal honor with the air ring.  Maybe that is the honor exchange that didn't happen?

**Comment by jeremylarner** [comment]
There were two bugs (trigger during mil and honor transfer goes the wrong way) - both have been fixed already, and should be on the server shortly
