### ISSUE TITLE
Young Rumormonger - Rules Hiccup

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#662]
If a dishonored character is about to become dishonored again (by losing a battle while having Pride, for example) the prompt to use Rumormonger appears and, if clicked, will let you move the effect.

Since no one was going to "be dishonored" there is nothing for the Rumormonger to respond to and the prompt shouldn't appear.

**Comment by jeremylarner** [comment]
Coincidently, I just had this discussion with someone else.  I think you're probably right, but I'd like to get clarification from the devs before I change it.  The question has been submitted, and I'm waiting on a ruling.  If I haven't had one before the game leaves beta, I might change it - I'll see if I've changed my mind by then...

**Comment by YogoGohei** [comment]
If you had that discussion on the facebook group, it's not a coincidence since I asked this question there before posting this bug report :)

**Comment by YogoGohei** [comment]
FYI.  From the fantasy flight forums:

The question:

In Legend of the Five Rings, during a conflict at my Shameful Display province, say I target one of my characters and one of my opponent's dishonored characters. If I honor my own character, can I trigger the Young Rumormonger's interrupt to dishonor an opponent's character who isn't participating, even though the character originally targeted to dishonor was already dishonored?

Nate's response: 

From the Rules Reference, under “Personal Honor” :

“A character with a dishonored status token cannot become dishonored.”

In your example, the opponent’s character is already dishonored. This means that the dishonor part of the Shameful Display effect will fail to resolve on the character. Therefore, that character does not meet the criteria of the Young Rumormonger: “when a character would be dishonored,” and you could not trigger the Rumormonger’s ability in this scenario.

**Comment by jeremylarner** [comment]
Thanks for letting me know - I have one more question that I'm waiting for a ruling on, but I appreciate you following up on this.

**Comment by jeremylarner** [comment]
I'm still not sure what happens when I Rumormonger redirects both SD effects on to the same target, but I've implemented a fix for dishonoring triggers on targets which can't be dishonored #739
