### ISSUE TITLE
Flip cards in provinces

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#663]
If you accidentally flip a card in a province, there is no way to flip it back down.

Related question: Why do I need to click on cards in provinces to flip them up?  With everything else automated at this point, I am surprised that isn't automated to have them just flip on their own at the beginning of the dynasty phase.

**Comment by jeremylarner** [comment]
It could be very easily automated.  Some people really like doing it themselves.  I could automate it, leave it, or make it an option in settings - not sure which would be better.  Something that does seem to cause a problem is that people flip early, and then have their new card discarded automatically at the end of the turn.  If we decide to leave it as is, I think click to flip should be disabled outside of the dynasty phase.

**Comment by jeremylarner** [comment]
Added in #752
