### ISSUE TITLE
Visible opponent's dynasty cards during setup

### ISSUE THREAD

**Issue by Kwaice** [gryffon/ringteki#668]
![screen shot 10-24-17 at 06 33 pm](https://user-images.githubusercontent.com/25953788/31956022-7c822aa4-b8ea-11e7-8803-70e0e3379596.PNG)

It seems that if you don't mulligan your dynasty card during setup, your opponent can then see them greyed out even before mulliganing conflict cards.

**Comment by jeremylarner** [comment]
Thanks for the report - fixed in #670
