### ISSUE TITLE
Suggestion: Markers to indicate lasting effects

### ISSUE THREAD

**Issue by AKWolff037** [gryffon/ringteki#672]
During a game a character used Banzai!, targeting 2 different characters in the challenge.  He had 3 characters with the same name in the challenge so there was no way to determine which ones had been buffed by the Banzai and which was not.

**Comment by jeremylarner** [comment]
So I was thinking about how we could solve this problem, and I wonder if we can use display effects on a character using mouseover text?

**Comment by AKWolff037** [comment]
My original thought would be to use markers similar to the Fate markers, but with military and political icons.  Either displaying total value, or total modifications.  Total value might be more useful in the long run.

I'm not a huge fan of mouseover text because it won't work well on mobile or tablet, though it might be a better way to display each individual lasting effect and its source.

**Comment by jeremylarner** [comment]
That's true, I hadn't thought about the mobile/tablet issue.  I don't really want to implement a solution which only half solves the problem (if I do mil/pol buffs, someone will complain that they don't know who ambusher targeted, or whatever).  Do mobile/tablet users not get to use the card zoom either?

**Comment by jamesoddy** [comment]
Skill modifiers are now visible thanks to #3257
