### ISSUE TITLE
Tattooed Wanderer - No Covert Activation

### ISSUE THREAD

**Issue by lufia22** [gryffon/ringteki#675]
When I attacked with a character equipped with Tattooed Wanderer, it did not initiate Covert. I have not tested to see if this is a universal Covert issue (I play Lion, so not much access to Covert) or if it's just Tattooed Wanderer.

EDIT: And no, the opposing character did not have Covert on them. It was a Kakita Kaezin with a Spyglass attached.

**Comment by jeremylarner** [comment]
Covert is implemented by clicking on the opposing players characters while declaring an attack.  Did you try (presumably unsuccessfully) clicking on your opponent's characters? Did the prompt say 'Choose characters to covert' when you clicked 'Initiate conflict'?

**Comment by lufia22** [comment]
I did not try that. I was not aware that was how to activate Covert. I thought it was a trigger from declaring an attacker with covert.

**Comment by jeremylarner** [comment]
It does maybe need an extra prompt if the attacker doesn't use it.  The idea was to let people visualise attacks better so they could change their mind.

**Comment by jeremylarner** [comment]
Added an extra prompt #736
