### ISSUE TITLE
Update How To Play

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#705]
How to play needs the current section on manual mode removing, and some explanation about menus.  Also maybe remove the chat commands which are now included in menus?

**Comment by gryffon** [comment]
I think the chat commands can stay. Having them, but not being used is handy, as long as they're both doing the same things.

**Comment by jeremylarner** [comment]
I wasn't planning to remove them from the game, just maybe from the how to play page.  Happy to leave them in there as well though if you think that would be better

**Comment by jeremylarner** [comment]
Done in #845
