### ISSUE TITLE
Hard to tell who's attacking when deciding whether to react with "Rally to the Cause"

### ISSUE THREAD

**Issue by Rodigee** [gryffon/ringteki#717]
When deciding whether to react with Rally to the Cause, the province that lets you switch the conflict type, you can't tell who is attacking because your opponent's card are black in white since the program is waiting for a response from the modal popup.

**Comment by jeremylarner** [comment]
I think the best way to make this clearer is probably to add an additional setting to 'cardSelect' which only greys out the player's cards, not their opponent's

**Comment by Rodigee** [comment]
Yes, that sounds like a good idea.
