### ISSUE TITLE
Ambush letting player take opponent's Scorpion characters

### ISSUE THREAD

**Issue by TLFJ** [gryffon/ringteki#728]
Just ran into this in a Scorpion Mirror. Game was over, but my opponent noticed my characters were highlighted, so we tried it, and it let him take my Shoju. It also didn't refill the province.

![ambush bug](https://user-images.githubusercontent.com/33043192/32202195-6f7bba98-bdb1-11e7-8267-858b45a90d84.PNG)

Ambush:
![ambush](https://user-images.githubusercontent.com/33043192/32202243-b3cae7b4-bdb1-11e7-9394-56c8e12c93f1.jpg)

**Comment by jeremylarner** [comment]
Thanks for the report - I particularly appreciate you taking the time to make a screenshot!  Fix submitted #730
