### ISSUE TITLE
Target informations enchance needed.

### ISSUE THREAD

**Issue by Sliski** [gryffon/ringteki#737]
1. When there are more than single character with the same name on the table, there are no indicators wich character is a target of the effect.
2. During prompt for interrupt player is not aware of the choosen options (e.g. court games) nor targets.

**Comment by jeremylarner** [comment]
1.  This is a known issue, and I'm interested in suggested solutions.  There are two possibilities on the table:
 - add mouseover text to cards which tells you what buffs they have, and whether they have used their 
abilities. Drawback: tablets don't get mouseover text.
 - add tokens representing buffs (like fate and honor tokens atm).  Drawback: scales very badly with additional effects and abilities.
2. Not knowing the option for a select ability like court games is a known issue.  You should see targets of targeted abilities (e.g. Assassination).  Can you give me some more info on what ability you couldn't see targets for?

**Comment by Sliski** [comment]
1. How about an (+) or (i) icon in the corner of the card?
-hover over will show lasting effects and other informations,
-click on the icon will do the same, but it wont disappear untill you click anywhere (an X icon in the information box would be good for it too).
Approach above should combine your solutions pros and cons to make balanced one.
2. I'll try to look for specific situation to make screenshot/better descritpion of the issue.

**Comment by jeremylarner** [comment]
I like your solution to 1) but I think it will require quite a bit of UI work.  I'll add to my list of requested enhancements

**Comment by Sliski** [comment]
Update to 2.
Scenario:
1. Player plays Banzai!.
2. Player is asked about interrupts:
![image](https://user-images.githubusercontent.com/33237900/32253972-42440d08-be9e-11e7-8348-72e01d322f0f.png)
At this point player is unaware about choosen target, the target is shown in log after passing: "Sliski uses Banzai! to grant 2 military skill to Favored Niece".

**Comment by jeremylarner** [comment]
Thanks for the extra info - that's really helpful.  I'll try and sort this out.

**Comment by jeremylarner** [comment]
Fix submitted for 2) #749

**Comment by jamesoddy** [comment]
Active skill modifiers are now visible thanks to #3257 
Closing this ticket.
