### ISSUE TITLE
Stronghold didn't break with correct amount of skill

### ISSUE THREAD

**Issue by chjaeggi** [gryffon/ringteki#743]
After my last attack the stronghold didn't break:
It was Yojin No Shiro with Ancestral Lands under it. So 5 for the province 5 extra for Ancestral Lands and then +2 from Stronghold. But then chat log:

munchli21 won a conflict 12 vs 0
vyslav loses 1 honor for not defending the conflict
munchli21 resolved the ring
munchli21 has chosen to pass
vyslav has chosen to pass
vyslav has chosen to pass his conflict opportunity

**Comment by jeremylarner** [comment]
Thanks for the report, and the details!  Replicated and fix submitted #748
