### ISSUE TITLE
Passing conflict makes undefined conflict w/o attackers nor defenders.

### ISSUE THREAD

**Issue by Sliski** [gryffon/ringteki#744]
Starting from today, after passing a conflict undefined conflict with no attackers and defenders is created:
![image](https://user-images.githubusercontent.com/33237900/32253867-8f02fefc-be9d-11e7-9357-5b2d1cc04ddd.png)

**Comment by jeremylarner** [comment]
Thanks for the report and the screenshot! It really helps - fix submitted #747
