### ISSUE TITLE
Missing action windows in fate and regroup phase

### ISSUE THREAD

**Issue by ainsleyc** [gryffon/ringteki#763]
I believe that there are currently 2 missing action windows: one in the fate phase, and one in the regroup phase. See reference:

https://imgur.com/a/oC4Jn

Thanks for this awesome project btw =D

**Comment by jeremylarner** [comment]
If you check your profile, you'll see that you can tell the game which action windows you want it to let you act in.  Fate and Regroup are unchecked by default (because most players don't use them very much), but if you're playing a deck which wants to act in those phases, just check them.
