### ISSUE TITLE
Cautious Scout vs Pilgrimage - not able to use ring ability

### ISSUE THREAD

**Issue by Mortimer89** [gryffon/ringteki#765]
When I attacked with Cautious Scout alone Pilgrimage province I was not able to use ring ability after I won conflict despite Scout remove text from province. 
Cautious Scout text:
_While this character is attacking alone, treat the defending province as if its printed text box were blank (except for Traits)._

**Comment by jeremylarner** [comment]
thanks for the report! Fix submitted #766
