### ISSUE TITLE
Steadfast Samurai

### ISSUE THREAD

**Issue by Kwaice** [gryffon/ringteki#799]
Steadfast Samurai is discarded at the beginning of the fate phase even if you have 5 more honor than your opponent.

I also had an inconsistent state at the beginning of the fate phase so not sure if the problem comes from the card or not.

**Comment by jeremylarner** [comment]
I can't replicate this - can you give me any more details?

**Comment by Kwaice** [comment]
Mmm, i can't replicate it either now. Looks good to me. Thank you for looking into it.
