### ISSUE TITLE
Unit Tests are currently a horrible mess

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#8]
The unit tests desperately need to be cleaned up. 

- Need to remove old tests that no longer apply.
- Need to create new tests for the added code.

This will be very beneficial, in that the CI results will actually become more meaningful.

**Comment by SnarkAttack** [comment]
I'll start by fixing up all the helper classes so that the tests can at least run properly, and after it gets pushed we can go from there.

**Comment by SnarkAttack** [comment]
I've fixed a bunch of these, but a lot of the remaining ones will require the conflict phase and card implementation, so I'll put them on hold for a bit.

**Comment by gryffon** [comment]
This is much better now, and I think future issues can be treated separately.
