### ISSUE TITLE
Invariant Violation: Attempted to update component `Connect(GameLobby)` that has already been unmounted (or failed to ...

### ISSUE THREAD

**Issue by jeremylarner** [gryffon/ringteki#825]
https://sentry.io/ringteki-team/ringteki/issues/398136967/

```
Invariant Violation: Attempted to update component `Connect(GameLobby)` that has already been unmounted (or failed to mount).
  at next (bundle.min.js:147351:21)
  at callbacks (./client/Application.jsx:99:13)
...
(45 additional frame(s) were not displayed)
```

**Comment by gryffon** [comment]
I think this might just be a user who has a bad client state. It's hard to tell for certain. 
Online this says it comes from doing a setState in your render function.
I've only discovered one place that happens in the code(in Profile, I have a change for it).

But this is referring to the game lobby.

**Comment by jeremylarner** [comment]
Yeah, could be a bad client issue.  It raised flags for me because it's been a consistent issue for the last 14 hours.  But it's all the same browser (Firefox) and OS (Windows 7) so that's consistent with a single user with a bad client.
