### ISSUE TITLE
borderlands fortification

### ISSUE THREAD

**Issue by j8wright** [gryffon/ringteki#826]
borderlands fortification disappears when i try to use its ability.  i flipped the facedown province and it wasnt there (so it doesnt just move and flip facedown), but when i used a hida guardian it added a +2 for the borderlands holding even though it was not showing.  
people say this card is garbage, but i'm sure theres a way to make it work, so i hope this helps

**Comment by jeremylarner** [comment]
Thanks for the bug report! Fix submitted #828  - for what it's worth, I think Borderlands Fortification is very under-rated
