### ISSUE TITLE
Blackmail issues.

### ISSUE THREAD

**Issue by Sliski** [gryffon/ringteki#836]
Log from game:
Sliski uses Blackmail to take control of Moto Youth
Lammia uses Warrior Poet to reduce the skill of all Sliski's characters
Sliski plays Fiery Madness, attaching it to Warrior Poet
Lammia has chosen to pass
Sliski has chosen to pass
Sliski won a  conflict 3 vs 2
Moto Youth cannot participate in the conflict any more and is sent home bowed

Problems:
1. Missleading information "Moto Youth cannot participate in the conflict any more and is sent home bowed" when the effect of Blackmail ends appears. Character should just bow and go to owner's home.
2. Warrior Poet ability doesn't work on blackmailed characters.

**Comment by jeremylarner** [comment]
Thanks for the report.  I've had a look at this, and I can see a bug with Warrior Poet, but I'm not sure it's the same as the one you had.  Can you remember who was in the conflict on both sides?  Was it military or political? Did either player have the favor?

Also, if you have a situation like this again, if you could grab a screenshot it is extremely helpful in tracking down bugs.

**Comment by Sliski** [comment]
I do not remember who had got the favor. Warrior Poet and Moto Youth were attacking, noone was declared as defender. It was 1st Military conflict this round.

**Comment by jeremylarner** [comment]
So you should have won 2 (or 3 with favor) vs 0 (or 1 with favor)?
