### ISSUE TITLE
Hotaru's reaction trigger from winning a political conflict did not happen.

### ISSUE THREAD

**Issue by almond55** [gryffon/ringteki#840]

**Comment by jeremylarner** [comment]
I can't replicate this - can you give me any more details?  In future, if you can submit a screenshot with a bug report, it makes my life a lot easier

**Comment by almond55** [comment]
Just try to win a political conflict. There's no window that asks if Hotaru wishes to trigger the ring effect again, like before.

**Comment by jeremylarner** [comment]
I can't replicate this at all.  Attacking with Hotaru alone for a political conflict of any ring allows me to trigger her reaction
