### ISSUE TITLE
Doji Gift Giver, Bow/Unbow, and Conflicts

### ISSUE THREAD

**Issue by nmetken** [gryffon/ringteki#847]
The Crane Doji Gift Giver allows the player to pay a fate to bow a participating character in a challenge, currently the UI allows the player to select any character to bow even ones not outside the challenge.  In the game we played we could not figure out a way to manually unbow/bow a character.  Would be nice to have the ability to do so.  Also if possible could characters participating in a conflict be moved to a central location away from the home area as well as be highlighted as participating in conflicts?  Would be a nice visual touch helpful during conflict phases.  Great work on the site!

**Comment by jeremylarner** [comment]
Thanks for the bug report - fix submitted #849 .  

To bow characters, use manual mode (/manual) then click the character.

The problem with moving characters forward is that it makes the game even harder for people with small screens.
