### ISSUE TITLE
Waiting for undefined - Keeper Initiate?

### ISSUE THREAD

**Issue by YogoGohei** [gryffon/ringteki#860]
When my opponent is figuring out whether or not they are going to put Keeper Initiate into play after taking a ring, the message "Waiting for undefined" (or something to that effect) is displayed to me while they are making their decision.

**Comment by jeremylarner** [comment]
I think this is actually when they're deciding whether to resolve the ring, or who to target with it, and I think it should be fixed in #844
That change is on the development branch though, so you probably won't see a fix until ToA cards are released.

**Comment by YogoGohei** [comment]
After many more games, yes, I think this is Ring of Fire.
