### ISSUE TITLE
Display of Power bug

### ISSUE THREAD

**Issue by Arbuzio** [gryffon/ringteki#886]
DoP asks to resolve a ring, you click yes - nothing happens and it asks again
![image](https://user-images.githubusercontent.com/32962101/32548675-c984b090-c486-11e7-9e77-7544da8ee6c0.png)

**Comment by Arbuzio** [comment]
jigoku.online

**Comment by jeremylarner** [comment]
Thanks for the report, and especially the screenshot! This is fixed in #873
