### ISSUE TITLE
Yokuni + Cloud the mind

### ISSUE THREAD

**Issue by Arbuzio** [gryffon/ringteki#887]
1) yokuni is in conflict bowed
2) yokuni copies niten master ability
3) cloud the mind is played on yokuni
4) nothing happens

2 problems;
1) i dont know if he readies right away because of cloud the mind
2) AFTER it if you attach something to him - still doesnt use niten master ability

**Comment by Arbuzio** [comment]
jigoku.online

**Comment by jeremylarner** [comment]
Thanks for the report - fix submitted #888
