### ISSUE TITLE
Consistency Issues In Card Data

### ISSUE THREAD

**Issue by SnarkAttack** [gryffon/ringteki#9]
Going though the Going through the tests, I'm finding some consistency issues in where the correct data for certain card attributes is located. For example, in drawcard.getsummary.spec.js, the test thinks that setting the card's 'militaryskill' attribute is correct, but getSummary() actually uses an attribute that is part of 'cardData', which is itself an attribute of the original card. 

It doesn't really matter either way, but which one of those do we want to be correct? I'm honestly a big fan of never using the cardData attribute for anything once the card has been initialized, but it's a big enough change I want to give people a chance to weigh in.

**Comment by jeremylarner** [comment]
I agree with never using cardData past initialization
