### ISSUE TITLE
Scaling problems

### ISSUE THREAD

**Issue by Void2258** [gryffon/ringteki#902]
When the card scaling is set to large or extra large, the cards cover part of the lower bar, making it impossible to see your own honor, conflict types, or first player marker.
![Large card example](https://user-images.githubusercontent.com/6126362/32579607-aa267c8c-c4af-11e7-86ca-2a5b0866bfa2.png)

**Comment by Void2258** [comment]
Can confirm issue is even worse with cards on Extra Large. it's basically unplayable at this point.
![Extra Large example](https://user-images.githubusercontent.com/6126362/32582570-775e4e34-c4bd-11e7-8a38-f343c6d9134d.png)

**Comment by jeremylarner** [comment]
Fixed in #1761
