### ISSUE TITLE
Card view during selection

### ISSUE THREAD

**Issue by Void2258** [gryffon/ringteki#915]
There is no card view during selections (ie card draws, such as Agasha Swordsmith). You get a list of names, but no way to see the cards. You then have to stop everything while you go hunting through a wiki or reference for the cards. We need to be able to view the card ANY TIME we need to make a selection.

**Comment by YogoGohei** [comment]
To throw in my two cents on this one, it would be nice if the cards always came up in a window similar to when you click on a discard pile or click on your province deck at the beginning of the game. 

Thumbnails for selection, with a full card view on mouseover.

**Comment by jeremylarner** [comment]
When we're not dealing with 20 new cards a week, I'd like to see if we can repurpose the popup boxes and use them generally.

In the meantime, I've added mouseover functionality to the selection menu for e.g. Agasha Swordsmith, so you'll get a zoomed in version of cards as you mouseover the buttons. #921
