### ISSUE TITLE
IE has a display bug with the playfield not going to the top of the window

### ISSUE THREAD

**Issue by gryffon** [gryffon/ringteki#920]
![untitled](https://user-images.githubusercontent.com/6053185/32618797-b103c25c-c546-11e7-8811-ae2183e111f5.png)

**Comment by devofdisaster** [comment]
I've had this locally in Firefox, and I _think_ I took care of that in #1092 . 
Need to check whether this still happens after that one is merged.

**Comment by jeremylarner** [comment]
Is this fixed now? @gryffon

**Comment by gryffon** [comment]
Looks resolved.
