### ISSUE TITLE
Resolving an Assassination on an honoured character displays a server error

### ISSUE THREAD

**Issue by SDchk** [gryffon/ringteki#949]
Observed: Playing an Assassination and targeting an honoured character will display a server error in chat, and the character is not discarded. The Assassination is effectively cancelled, although the game continues as usual.

Steps to reproduce:
- Start a game
- Have opponent honour a 2 cost or lower character
- Proceed to a conflict
- Use Assassination on the character
- Observe server error

Reproduced twice in two games (2/2) - my Daidoji Nerishina the first time, opponent's Brash Samurai the second time (Both were honoured but I'm guessing that's the cause)

Expected: Server error is not displayed and the character is discard as usual

![image](https://user-images.githubusercontent.com/33578635/32691859-2189b3a4-c706-11e7-843c-1c41aac1086c.png)

**Comment by SDchk** [comment]
Workaround: remove fate from the character using console command, manually remove it from the conflict if needed with /manual, and then make sure to bow it as well so it doesn't count for Imperial Favour.
And then be nice and doesn't use the character rest of the round.

**Comment by jeremylarner** [comment]
Thanks for the detailed report - I've submitted a fix for this bug #950. I really appreciate the chat log and the replication instructions though!
