### ISSUE TITLE
Crane Guest of Honor not allowing events to be played despite having a cloud the mind on it.

### ISSUE THREAD

**Issue by nmetken** [gryffon/ringteki#952]
During our game the Guest of Honor had a Cloud the Mind attached to it.  The opponent tried to play Mirumoto's Fury which was a legal play at the time and he was not able to do so.  We opted to discard the card and manually engage the effect however the game then froze up and would not allow me to enter manual mode to manually bow the guest nor could I type in the chat or do anything.

**Comment by jeremylarner** [comment]
I can't replicate this - are you sure there wasn't another reason why Mirumoto's Fury couldn't be played? Maybe no facedown provinces, or not enough fate?
