### ISSUE TITLE
Fate Phase - Inconsistent state

### ISSUE THREAD

**Issue by stefanhoard** [gryffon/ringteki#953]
The error appeared during Fate Phase (step 4) of the first round.  During this time we were unable to perform any actions or continue with the game. This happened twice in two separate games with my opponent hosting both (same player).

"A Server error has occurred processing your game state, apologies. Your game may now be in an inconsistent state, or you may be able to continue. The error has been logged."

I was using "Version 62.0.3202.89 (Official Build) (64-bit)" of Google Chrome on Windows 10. I am unsure as to what the other player was using.

Edit: I've been told this has happened with Assassination and to switch to /manual and move the characters manually as a work around

**Comment by stefanhoard** [comment]
Forgot to mention I was using "Version 62.0.3202.89 (Official Build) (64-bit) of Google Chrome". I am unsure as to what the other player was using.

**Comment by jeremylarner** [comment]
Thanks for the report - Fix submitted #972
