### ISSUE TITLE
Conflict hand is not showing up

### ISSUE THREAD

**Issue by Christy42** [gryffon/ringteki#955]
Hi I tried to play today but my conflict cards never showed up.  I assume it is meant to be on the right from the picture in the #948 bug.
![jigokusnapshot](https://user-images.githubusercontent.com/20259602/32694032-26445192-c72e-11e7-9428-93e14b9f3913.PNG)

**Comment by jeremylarner** [comment]
You need to zoom out, or scroll around and find it.  Which browser are you using?

**Comment by Christy42** [comment]
Chrome
