### ISSUE TITLE
Too many restricted attachments

### ISSUE THREAD

**Issue by Kwaice** [gryffon/ringteki#976]
![screen shot 11-12-17 at 01 43 pm](https://user-images.githubusercontent.com/25953788/32699057-dd611f32-c7af-11e7-95c7-38c97f46b78e.PNG)

After moving an ornate fan to my Giver of Gifts, the game told me i had too many restricted attachments even if i only had, after the move, 2 ornate fans and 1 Favored Mount.

**Comment by jeremylarner** [comment]
Thanks for the report, and the screenshot! Fix submitted #992
