### ISSUE TITLE
Seeker of Knowledge interaction bug

### ISSUE THREAD

**Issue by Icaryder** [gryffon/ringteki#982]
Was recently playing a game, had seeker of knowledge and fearsome mystic attacking. Used mystic's effect and nothing happened, should've discarded fate from 1 of my opponent's characters (they had glory 1). Looked at other things and noticed the totals were wrong, as mystic was honoured, but I was -2 on the totals screen. The rest of the things connected to Seeker seem to work fine.

**Comment by jeremylarner** [comment]
Thanks for the report - fix submitted #984
