### ISSUE TITLE
Kakita Kaezin duel bug

### ISSUE THREAD

**Issue by Yfkes** [gryffon/ringteki#987]
An honored Kakita Kaezin (Crane) stats 5/3 vs Tattooed Wanderer stats 2/1. With a bid of one each the wanderer should have been sent home. Instead it remained in the conflict blocking.

*love the site, thx for the huge effort!

**Comment by jeremylarner** [comment]
Kakita Kaezin: "Action: While this character is participating in a conflict, your opponent must choose a participating character he or she controls – challenge that character to a  duel. If this character wins, move each character **not** involved in the duel home. If it loses, send it home."

Kaezin won, neither duel participant was sent home.  Sounds like it's working as designed?

Let me know if I misunderstood something

**Comment by Yfkes** [comment]
Hey 

When I read it like this.. it looks like I'm the one misinterpreting the text. 

" If this character wins ". I was under the impression that this was referring to the latest mentioning of a character, being the one of the opponent. I guess it both makes sense. If you lose you get stuck with an opponent more powerful (unless the honorbid was much higher), else you send an opponent home and you get stronger in the general conflict. 

I'm pretty new to the game so I'm guessing your interpretation is the correct one. 

Thank you for the quick reply. 

Best regards, 

Yves Laenen 


Van: "jeremylarner" <notifications@github.com> 
Aan: "gryffon/ringteki" <ringteki@noreply.github.com> 
Cc: "yveslaenen" <yveslaenen@telenet.be>, "Author" <author@noreply.github.com> 
Verzonden: Maandag 13 november 2017 11:35:33 
Onderwerp: Re: [gryffon/ringteki] Kakita Kaezin duel bug (#987) 



Kakita Kaezin: "Action: While this character is participating in a conflict, your opponent must choose a participating character he or she controls – challenge that character to a duel. If this character wins, move each character not involved in the duel home. If it loses, send it home." 

Kaezin won, neither duel participant was sent home. Sounds like it's working as designed? 

Let me know if I misunderstood something
