### ISSUE TITLE
Yokuni Copying and Using Ability Locked the Prompt

### ISSUE THREAD

**Issue by b-togo** [gryffon/ringteki#995]
During a conflict with Togashi Yokuni (mine) and Shrewd Yasuki (opponents) in play.
There is a holding in play controlled by my opponent (Shrewd Yasuki ability is turned on). 
I use Togashi Yokuni to copy Shrewd Yasuki.
Opponent passes.
I use Togashi Yokuni to use the ability copied from Shrewd Yasuki.
The prompt to pick which card goes into my hand is shown (Court Games, Indomitable Will) but clicking the button to put either card in my hand does nothing.

**Comment by jeremylarner** [comment]
Thanks for the report - I'm pretty sure I know what the problem is.

**Comment by jeremylarner** [comment]
Fix submitted #1015
